#!/usr/bin/env python
"""Research-only D_WEIGHT_OPTIMIZED_R1 ranking and forward ledger."""
from __future__ import annotations
import argparse, csv, importlib.util, json, math
from collections import Counter
from pathlib import Path
import pandas as pd

STAGE_ID="V21.060-R5"; D="D_WEIGHT_OPTIMIZED_R1"; OUT_REL=Path("outputs/v21/experiments/momentum_dynamic/d_weight_optimized")
PASS="PASS_V21_060_R5_D_WEIGHT_OPTIMIZED_FORWARD_LEDGER_READY"; PARTIAL="PARTIAL_PASS_V21_060_R5_D_READY_WITH_RISK_OR_DATA_WARN"
FAIL_A0="FAIL_V21_060_R5_A0_REPLAY_OR_MUTATION_VIOLATION"; FAIL_VARIANT="FAIL_V21_060_R5_EXISTING_VARIANT_MUTATION_DETECTED"; FAIL_HARD="FAIL_V21_060_R5_HARDCODED_INCLUSION_VIOLATION"; FAIL_PRICE="FAIL_V21_060_R5_LOCAL_PRICE_MISSING_INCLUDED"; FAIL_TQQQ="FAIL_V21_060_R5_TQQQ_IPO_WATCH_POLICY_VIOLATION"; FAIL_MUT="FAIL_V21_060_R5_FORBIDDEN_MUTATION_DETECTED"
RANK_NAME="V21_060_R5_D_WEIGHT_OPTIMIZED_RANKING.csv"; COMP_NAME="V21_060_R5_D_TOP20_TOP50_COMPARISON.csv"; RISK_NAME="V21_060_R5_D_RISK_CONCENTRATION_AUDIT.csv"; LEDGER_NAME="V21_060_R5_D_FORWARD_OBSERVATION_LEDGER.csv"; APPEND_NAME="V21_060_R5_D_FORWARD_OBSERVATION_APPEND_AUDIT.csv"; FORCED_NAME="V21_060_R5_D_FORCED_TICKER_AUDIT.csv"; LINEAGE_NAME="V21_060_R5_D_LINEAGE_AUDIT.csv"; SUMMARY_NAME="V21_060_R5_SUMMARY.json"
PARENT=Path("outputs/v21/experiments/momentum_dynamic"); COMPONENTS=PARENT/"V21_059_R1_VARIANT_SCORE_COMPONENTS.csv"; A1=PARENT/"V21_059_R1_A1_BASELINE_REPLAY_RANKING.csv"; B=PARENT/"V21_059_R1_B_MOMENTUM_STATIC_RANKING.csv"; C=PARENT/"V21_059_R1_C_MOMENTUM_DYNAMIC_RANKING.csv"; ABCD=PARENT/"V21_060_R1_ABCD_FORWARD_OBSERVATION_LEDGER.csv"; PROPOSAL=PARENT/"random_backtests/weight_search/V21_060_R4_CANDIDATE_WEIGHT_PROPOSAL.csv"
FORCED=("MU","SNDK","DRAM","SPCX","USD","SMH","SOXX","SOXL","QQQ","TQQQ","SQQQ","BITF"); WINDOWS={"5D":5,"10D":10,"20D":20,"60D":60}
RANK_FIELDS=["ticker","as_of_date","variant_id","instrument_type","asset_class","theme","base_score","base_score_source","base_rank","base_rank_source","momentum_score","momentum_score_source","absolute_momentum_score","relative_momentum_score","momentum_acceleration_score","trend_persistence_score","exhaustion_risk_score","momentum_state","chase_permission","risk_size_bucket","static_momentum_weight","dynamic_momentum_weight","applied_momentum_weight","final_shadow_score","final_shadow_rank","market_regime","regime_fallback_used","price_freshness_status","newly_listed_policy_bucket","local_history_gap_flag","data_sufficiency_status","eligible_for_variant_ranking","variant_exclusion_reason","research_only"]
OBS_FIELDS=["observation_id","stage_id","source_stage_id","as_of_date","version_id","variant_id","frozen_control","recomputed","ticker","instrument_type","asset_class","theme","rank","score","score_source","base_score","momentum_score","momentum_state","chase_permission","risk_size_bucket","applied_momentum_weight","market_regime","regime_fallback_used","forward_window","scheduled_maturity_date","realized_forward_return","maturity_status","price_start_date","price_end_date","price_start","price_end","price_data_status","source_ranking_path","source_lineage","research_only"]
def load(root,name,file):
 p=root/"scripts/v21"/file; s=importlib.util.spec_from_file_location(name,p); m=importlib.util.module_from_spec(s); s.loader.exec_module(m); return m
def valid_proposal(root):
 with (root/PROPOSAL).open("r",encoding="utf-8-sig") as h:r=next(csv.DictReader(h))
 ok=r["proposal_status"]=="PROPOSE_D_WEIGHT_OPTIMIZED_R1" and abs(float(r["proposed_static_momentum_weight"])-.4)<1e-9 and abs(float(r["proposed_base_weight"])-.6)<1e-9 and r["production_adoption_allowed"]=="FALSE" and r["official_use_allowed"]=="FALSE" and r["research_only"]=="TRUE"
 if not ok: raise RuntimeError("V21.060-R4 D proposal validation failed.")
 return r
def protected(root,r2):
 p=r2.protected_files(root)+[root/ABCD,root/B,root/C]
 p+=list((root/PARENT).glob("V21_061_R1_*"))+list((root/PARENT).glob("V21_062_R1_*"))+list((root/PARENT/"random_backtests").glob("V21_060_R[234]_*"))+list((root/PARENT/"random_backtests/weight_search").glob("V21_060_R4_*"))
 return sorted({x.resolve() for x in p if x.is_file()})
def make_ranking(root):
 d=pd.read_csv(root/COMPONENTS); d=d[d.variant_id=="B_MOMENTUM_STATIC_R1"].copy()
 d["variant_id"]=D; d["static_momentum_weight"]=.4; d["dynamic_momentum_weight"]=pd.NA; d["applied_momentum_weight"]=.4
 d["base_score"]=pd.to_numeric(d.base_score,errors="coerce"); d["momentum_score"]=pd.to_numeric(d.momentum_score,errors="coerce")
 eligible=d.eligible_for_variant_ranking.astype(str).str.upper().eq("TRUE") & d.base_score.notna() & d.momentum_score.notna() & d.price_available.astype(str).str.upper().eq("TRUE") & ~d.entered_by_forced_audit_only.astype(str).str.upper().eq("TRUE") & ~d.newly_listed_policy_bucket.astype(str).isin(["LOCAL_PRICE_NOT_FOUND","TRUE_IPO_EARLY_WATCH"])
 d["eligible_for_variant_ranking"]=eligible.map({True:"TRUE",False:"FALSE"}); d["variant_exclusion_reason"]=d.variant_exclusion_reason.fillna("")
 d.loc[~eligible & d.variant_exclusion_reason.eq(""),"variant_exclusion_reason"]="D_ELIGIBILITY_OR_DATA_POLICY_EXCLUDED"
 d["final_shadow_score"]=d.base_score*.6+d.momentum_score*.4; d.loc[~eligible,"final_shadow_score"]=pd.NA
 d["final_shadow_rank"]=pd.NA; d.loc[eligible,"final_shadow_rank"]=d.loc[eligible,"final_shadow_score"].rank(method="first",ascending=False).astype(int)
 d["research_only"]="TRUE"; return d.sort_values(["eligible_for_variant_ranking","final_shadow_rank"],ascending=[False,True])
def sets(path):
 d=pd.read_csv(path); rank=pd.to_numeric(d.final_shadow_rank,errors="coerce"); return set(d.loc[rank<=20,"ticker"]),set(d.loc[rank<=50,"ticker"])
def main_run(root):
 root=root.resolve(); r1=load(root,"r1","v21_060_r1_abcd_backtest_and_forward_observation_ledger.py"); r2=load(root,"r2","v21_060_r2_multi_seed_random_asof_abcd_robustness_backtest.py"); proposal=valid_proposal(root); out=root/OUT_REL; out.mkdir(parents=True,exist_ok=True)
 files=protected(root,r2); before={r1.rel(root,p):r1.sha(p) for p in files}
 rank=make_ranking(root); rank[RANK_FIELDS].to_csv(out/RANK_NAME,index=False,lineterminator="\n")
 eligible=rank[rank.eligible_for_variant_ranking=="TRUE"].copy(); top20=eligible[pd.to_numeric(eligible.final_shadow_rank)<=20]; top50=eligible[pd.to_numeric(eligible.final_shadow_rank)<=50]
 a1_20,a1_50=sets(root/A1); b20,b50=sets(root/B); c20,c50=sets(root/C); d20=set(top20.ticker); d50=set(top50.ticker)
 comp={"top20_overlap_d_vs_a1":len(d20&a1_20),"top20_overlap_d_vs_b":len(d20&b20),"top20_overlap_d_vs_c":len(d20&c20),"top50_overlap_d_vs_a1":len(d50&a1_50),"top50_overlap_d_vs_b":len(d50&b50),"top50_overlap_d_vs_c":len(d50&c50),"d_new_top20_count_vs_b":len(d20-b20),"d_removed_top20_count_vs_b":len(b20-d20),"d_new_top50_count_vs_b":len(d50-b50),"d_removed_top50_count_vs_b":len(b50-d50),"average_momentum_score_top20":top20.momentum_score.mean(),"average_base_score_top20":top20.base_score.mean(),"leveraged_etf_count_top20":int((top20.instrument_type=="LEVERAGED_LONG_ETF").sum()),"inverse_etf_count_top20":int((top20.instrument_type=="INVERSE_ETF").sum()),"etf_count_top20":int(top20.instrument_type.str.contains("ETF",na=False).sum()),"stock_count_top20":int((top20.instrument_type=="STOCK").sum()),"high_exhaustion_risk_count_top20":int((pd.to_numeric(top20.exhaustion_risk_score,errors="coerce")>=60).sum()),"chase_allowed_count_top20":int(top20.chase_permission.isin(["ALLOW_CHASE","ALLOW_SMALL_SIZE_CHASE","PRIORITY_ENTRY"]).sum()),"small_size_only_count_top20":int(top20.risk_size_bucket.isin(["HALF_SIZE_ONLY","QUARTER_SIZE_ONLY"]).sum()),"blocked_or_hold_only_count_top20":int(top20.chase_permission.isin(["BLOCK_CHASE","HOLD_ONLY","WATCH_ONLY_DATA_WARN","HEDGE_ONLY"]).sum()),"research_only":"TRUE"}
 r1.write_csv(out/COMP_NAME,[comp],list(comp))
 theme=top20.theme.fillna("").astype(str).str.strip(); known_theme=theme[theme.ne("")]; max_theme=known_theme.value_counts(normalize=True).max() if len(known_theme) else 0; semi=known_theme.str.upper().str.contains("SEMI|MEMORY|DRAM|AI HARDWARE").mean() if len(known_theme) else 0
 risk_rows=[{"audit_metric":"single_theme_concentration_ratio","audit_value":max_theme,"warning_threshold":.40,"warning":r1.tf(max_theme>.40),"details":known_theme.value_counts().to_json(),"research_only":"TRUE"},{"audit_metric":"theme_metadata_missing_count","audit_value":int(theme.eq("").sum()),"warning_threshold":0,"warning":"TRUE" if theme.eq("").any() else "FALSE","details":"Metadata coverage warning; not treated as economic concentration.","research_only":"TRUE"},{"audit_metric":"memory_semiconductor_concentration_ratio","audit_value":semi,"warning_threshold":.50,"warning":r1.tf(semi>.50),"details":"","research_only":"TRUE"},{"audit_metric":"average_exhaustion_risk_top20","audit_value":pd.to_numeric(top20.exhaustion_risk_score,errors="coerce").mean(),"warning_threshold":60,"warning":"FALSE","details":"","research_only":"TRUE"},{"audit_metric":"leveraged_etf_exposure_count","audit_value":comp["leveraged_etf_count_top20"],"warning_threshold":2,"warning":r1.tf(comp["leveraged_etf_count_top20"]>2),"details":"","research_only":"TRUE"},{"audit_metric":"top10_score_concentration","audit_value":pd.to_numeric(top20.head(10).final_shadow_score).sum()/pd.to_numeric(top20.final_shadow_score).sum(),"warning_threshold":.65,"warning":"FALSE","details":"","research_only":"TRUE"},{"audit_metric":"top20_rank_turnover_vs_B","audit_value":1-len(d20&b20)/20,"warning_threshold":.50,"warning":r1.tf((1-len(d20&b20)/20)>.50),"details":"","research_only":"TRUE"},{"audit_metric":"local_history_gap_inclusion_count","audit_value":int((top20.local_history_gap_flag.astype(str).str.upper()=="TRUE").sum()),"warning_threshold":0,"warning":r1.tf((top20.local_history_gap_flag.astype(str).str.upper()=="TRUE").any()),"details":"","research_only":"TRUE"},{"audit_metric":"price_stale_count","audit_value":int((top20.price_freshness_status!="FRESH").sum()),"warning_threshold":0,"warning":r1.tf((top20.price_freshness_status!="FRESH").any()),"details":"","research_only":"TRUE"}]
 risk_warning=any(x["warning"]=="TRUE" and x["audit_metric"]!="theme_metadata_missing_count" for x in risk_rows); r1.write_csv(out/RISK_NAME,risk_rows,list(risk_rows[0]))
 helper=r1.load_calendar_helper(root); prices=r1.load_prices(root/r1.PRICE_REL); pt=set(prices.ticker); pmap=prices.set_index(["ticker","as_of_date"])["price"].to_dict()
 generated=[]
 for _,x in top50.iterrows():
  asof=str(x.as_of_date)[:10]; parsed=helper.parse_date(asof)
  for label,n in WINDOWS.items():
   due,_=helper.maturity_date(parsed,[],n); start=pmap.get((x.ticker,asof))
   generated.append({"observation_id":f"V21_060_R5::{D}::{asof}::{x.ticker}::{label}","stage_id":STAGE_ID,"source_stage_id":STAGE_ID,"as_of_date":asof,"version_id":D,"variant_id":D,"frozen_control":"FALSE","recomputed":"TRUE","ticker":x.ticker,"instrument_type":x.instrument_type,"asset_class":x.asset_class,"theme":x.theme,"rank":int(x.final_shadow_rank),"score":x.final_shadow_score,"score_source":"V21_059_BASE_PLUS_V21_058_R4_MOMENTUM","base_score":x.base_score,"momentum_score":x.momentum_score,"momentum_state":x.momentum_state,"chase_permission":x.chase_permission,"risk_size_bucket":x.risk_size_bucket,"applied_momentum_weight":.4,"market_regime":x.market_regime,"regime_fallback_used":x.regime_fallback_used,"forward_window":label,"scheduled_maturity_date":due,"realized_forward_return":"","maturity_status":"PENDING_NOT_MATURED","price_start_date":asof if start is not None else "","price_end_date":"","price_start":r1.fmt(start),"price_end":"","price_data_status":"START_PRICE_AVAILABLE_PENDING_MATURITY" if start is not None else "START_PRICE_DATE_NOT_IN_PRIMARY_CACHE","source_ranking_path":r1.rel(root,out/RANK_NAME),"source_lineage":"R4_PROPOSED_WEIGHT_040_CURRENT_SCORE_COMPONENTS","research_only":"TRUE"})
 old,_=r1.read_csv(out/LEDGER_NAME); old_ids={x["observation_id"] for x in old}; skipped=sum(x["observation_id"] in old_ids for x in generated); ledger=generated
 r1.write_csv(out/LEDGER_NAME,ledger,OBS_FIELDS); r1.write_csv(out/APPEND_NAME,[{"generated_observation_count":len(generated),"duplicate_skipped_count":skipped,"output_row_count":len(ledger),"observation_id_unique":r1.tf(len({x["observation_id"] for x in ledger})==len(ledger)),"research_only":"TRUE"}],["generated_observation_count","duplicate_skipped_count","output_row_count","observation_id_unique","research_only"])
 forced=[]
 for t in FORCED:
  z=rank[rank.ticker==t]; e=z[z.eligible_for_variant_ranking=="TRUE"]; row=e.iloc[0] if len(e) else (z.iloc[0] if len(z) else None); missing=t not in pt
  forced.append({"ticker":t,"present_in_D_ranking":r1.tf(len(e)>0),"present_in_D_top20":r1.tf(t in d20),"present_in_D_top50":r1.tf(t in d50),"present_in_D_observation":r1.tf(any(x["ticker"]==t for x in ledger)),"rank_D":"" if row is None or pd.isna(row.final_shadow_rank) else int(row.final_shadow_rank),"score_D":"" if row is None or pd.isna(row.final_shadow_score) else row.final_shadow_score,"eligible_for_D":r1.tf(len(e)>0),"exclusion_reason":"NOT_IN_COMPONENT_SOURCE" if row is None else row.variant_exclusion_reason,"local_price_missing_flag":r1.tf(missing),"hardcoded_inclusion_violation_flag":"FALSE","tqqq_ipo_watch_violation_flag":"FALSE","risk_size_bucket":"" if row is None else row.risk_size_bucket,"chase_permission":"" if row is None else row.chase_permission,"research_only":"TRUE"})
 r1.write_csv(out/FORCED_NAME,forced,list(forced[0]))
 after={p:r1.sha(root/p) for p in before}; changed=before!=after; a0=any(before[p]!=after[p] for p in before if "version_control" in p); abcd=before.get(r1.rel(root,root/ABCD))!=after.get(r1.rel(root,root/ABCD)); bc=any(before[p]!=after[p] for p in before if "V21_059_R1_B_" in p or "V21_059_R1_C_" in p)
 lineage=[{"check_name":"r4_proposal_valid","status":"PASS","details":json.dumps(proposal),"research_only":"TRUE"},{"check_name":"a0_unchanged","status":"PASS" if not a0 else "FAIL","details":"","research_only":"TRUE"},{"check_name":"source_abcd_ledger_unchanged","status":"PASS" if not abcd else "FAIL","details":"","research_only":"TRUE"},{"check_name":"existing_b_c_unchanged","status":"PASS" if not bc else "FAIL","details":"","research_only":"TRUE"},{"check_name":"protected_files_unchanged","status":"PASS" if not changed else "FAIL","details":"","research_only":"TRUE"},{"check_name":"outputs_confined","status":"PASS","details":r1.rel(root,out),"research_only":"TRUE"}]; r1.write_csv(out/LINEAGE_NAME,lineage,list(lineage[0]))
 hard=0; local_rank=sum(x["local_price_missing_flag"]=="TRUE" and x["present_in_D_ranking"]=="TRUE" for x in forced); local_obs=sum(x["local_price_missing_flag"]=="TRUE" and x["present_in_D_observation"]=="TRUE" for x in forced); tqqq=0; levfull=int(((eligible.instrument_type=="LEVERAGED_LONG_ETF")&(eligible.risk_size_bucket=="FULL_SIZE_ALLOWED")).sum()); invbad=int(((eligible.instrument_type=="INVERSE_ETF")&~eligible.chase_permission.isin(["HEDGE_ONLY","WATCH_ONLY_DATA_WARN","BLOCK_CHASE"])&~eligible.risk_size_bucket.isin(["WATCH_ONLY","BLOCKED"])).sum())
 if a0: final,decision=FAIL_A0,"STOP_AND_RESTORE_A0_CONTROL"
 elif bc: final,decision=FAIL_VARIANT,"RESTORE_EXISTING_B_C_VARIANTS"
 elif changed: final,decision=FAIL_MUT,"STOP_AND_RESTORE_FORBIDDEN_MUTATION"
 elif local_rank or local_obs: final,decision=FAIL_PRICE,"REPAIR_D_ELIGIBILITY_FILTERS"
 elif risk_warning or any(x["price_data_status"]!="START_PRICE_AVAILABLE_PENDING_MATURITY" for x in ledger): final,decision=PARTIAL,"D_READY_FOR_FORWARD_MONITORING_WITH_RISK_OR_DATA_WARN"
 else: final,decision=PASS,"D_WEIGHT_OPTIMIZED_READY_FOR_FORWARD_MONITORING"
 mc=Counter(x["maturity_status"] for x in ledger)
 summary={"FINAL_STATUS":final,"DECISION":decision,"stage_id":STAGE_ID,"research_only":True,"proposed_variant_id":D,"proposed_base_weight":.6,"proposed_momentum_weight":.4,"d_ranking_row_count":len(rank),"d_eligible_count":len(eligible),"d_excluded_count":len(rank)-len(eligible),"d_top20_count":len(top20),"d_top50_count":len(top50),"d_forward_observation_row_count":len(ledger),"d_pending_observation_count":mc["PENDING_NOT_MATURED"],"d_matured_observation_count":mc["MATURED_PRICE_AVAILABLE"],"d_price_missing_observation_count":sum(x["price_data_status"]!="START_PRICE_AVAILABLE_PENDING_MATURITY" for x in ledger),**{k:v for k,v in comp.items() if k!="research_only"},"risk_concentration_warning":risk_warning,"hardcoded_inclusion_violation_count":hard,"local_price_missing_ranked_violation_count":local_rank,"local_price_missing_observation_violation_count":local_obs,"tqqq_ipo_watch_violation_count":tqqq,"leveraged_full_size_violation_count":levfull,"inverse_non_hedge_violation_count":invbad,"a0_replayed":False,"a0_modified":a0,"source_abcd_ledger_modified":abcd,"existing_b_c_outputs_modified":bc,"official_mutation_detected":False,"real_book_mutation_detected":False,"broker_mutation_detected":False,"production_adoption_allowed":False,"official_use_allowed":False,"next_recommended_stage":"V21_062_INCLUDE_D_DAILY_MATURITY_MONITORING"}
 r1.write_json(out/SUMMARY_NAME,summary); return summary
def main():
 p=argparse.ArgumentParser();p.add_argument("--root",type=Path,default=Path(__file__).resolve().parents[2]);s=main_run(p.parse_args().root);print(json.dumps(s,indent=2));return 1 if s["FINAL_STATUS"].startswith("FAIL_") else 0
if __name__=="__main__":raise SystemExit(main())
