tickers:
  - AA
  - AAL
  - AAPL
  - ABR
  - ACLS
  - ACM
  - ACMR
  - ADBE
  - ADMA
  - ADSK
  - AEHR
  - AEIS
  - AEVA
  - AFRM
  - AGX
  - ALAB
  - ALM
  - AMAT
  - AMC
  - AMD
  - AMKR
  - AMZN
  - ANET
  - APG
  - APH
  - APLD
  - APO
  - APP
  - ARGT
  - ARM
  - ASML
  - AVGO
  - AXON
  - BABA
  - BAC
  - BALL
  - BE
  - BIDU
  - BITF
  - BKNG
  - BLSH
  - BLTE
  - BN
  - BSX
  - BTDR
  - BW
  - BYND
  - CAI
  - CAMT
  - CARR
  - CART
  - CDNS
  - CEG
  - CHPT
  - CHRW
  - CHYM
  - CIEN
  - CIFR
  - CLF
  - CLH
  - CLS
  - CLSK
  - CMG
  - CNM
  - COF
  - COGT
  - COHR
  - COHU
  - CORZ
  - CPAY
  - CPNG
  - CRCL
  - CRDO
  - CRH
  - CRM
  - CRS
  - CRWD
  - CRWV
  - CSCO
  - CSGP
  - CVNA
  - D
  - DAKT
  - DAL
  - DASH
  - DB
  - DBVT
  - DDOG
  - DELL
  - DIS
  - DOCU
  - DUOL
  - ECL
  - EEM
  - ENPH
  - ENTG
  - EQIX
  - EQT
  - ET
  - ETN
  - ETR
  - EWY
  - EWZ
  - FCNCA
  - FIGR
  - FIX
  - FLEX
  - FLR
  - FLS
  - FLUT
  - FN
  - FORM
  - FWONK
  - GEHC
  - GEMI
  - GEV
  - GLW
  - GNRC
  - GOOG
  - GOOGL
  - GRAB
  - GS
  - GSG
  - GT
  - HIVE
  - HLT
  - HOOD
  - HPE
  - HTZ
  - HUBB
  - HUBS
  - HUM
  - HUT
  - IBIT
  - ICHR
  - IGV
  - INFY
  - INSM
  - INTC
  - IRDM
  - IREN
  - ISRG
  - IWM
  - IYW
  - JBL
  - JBS
  - JCI
  - JD
  - JHX
  - KEYS
  - KKR
  - KLAC
  - KLAR
  - KLIC
  - KNX
  - KRC
  - KVYO
  - KWEB
  - LBRT
  - LCID
  - LHX
  - LIN
  - LINE
  - LITE
  - LPLA
  - LRCX
  - LSCC
  - LYB
  - LYFT
  - MA
  - MCHP
  - MCK
  - MDB
  - MELI
  - META
  - MKSI
  - MNTN
  - MOD
  - MOH
  - MPLX
  - MPWR
  - MRVL
  - MSFT
  - MTSI
  - MTZ
  - MU
  - NAMS
  - NET
  - NFLX
  - NI
  - NOW
  - NRG
  - NTAP
  - NTRA
  - NU
  - NUVB
  - NVAX
  - NVDA
  - NVT
  - NXPI
  - OC
  - OKTA
  - OLMA
  - OLPX
  - OPCH
  - ORCL
  - PANW
  - PATH
  - PCOR
  - PCT
  - PDD
  - PFGC
  - PGNY
  - PI
  - PINS
  - PLTR
  - PLUG
  - PM
  - PONY
  - POWL
  - PSIX
  - PSTG
  - PTGX
  - PTON
  - PUMP
  - PWR
  - PYPL
  - QCOM
  - QQQ
  - QS
  - QSR
  - RBLX
  - RDDT
  - RERE
  - RH
  - RIOT
  - RKT
  - RNG
  - ROKU
  - RSP
  - RTX
  - RVMD
  - SANM
  - SATS
  - SCCO
  - SCHW
  - SE
  - SEI
  - SFIX
  - SFM
  - SHOP
  - SHW
  - SITM
  - SMCI
  - SMH
  - SMTC
  - SNDK
  - SNOW
  - SNPS
  - SOLS
  - SOXL
  - SOXX
  - SPOT
  - SPY
  - STG
  - STM
  - STUB
  - STX
  - TEAM
  - TER
  - TEVA
  - TIGR
  - TLN
  - TQQQ
  - TSEM
  - TSLA
  - TSM
  - TTD
  - TTMI
  - TTWO
  - TWLO
  - TWST
  - TXN
  - U
  - UAL
  - UBER
  - UNH
  - UPST
  - USFD
  - V
  - VECO
  - VEEV
  - VIAV
  - VIST
  - VMC
  - VRT
  - VST
  - WAB
  - WDAY
  - WDC
  - WHR
  - WING
  - WLK
  - WOLF
  - WULF
  - WVE
  - WWD
  - WYFI
  - XENE
  - XLF
  - XLK
  - XPO
  - XYZ
  - YPF
  - Z
  - ZG
  - ZS
