Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.35-R1"
Write-Host "PATCH_NAME: HISTORICAL_YAHOO_CACHE_EXPANSION_FOR_RANDOM_ASOF_BACKTEST"
Write-Host "CACHE_EXPANSION_ONLY: TRUE"
Write-Host "RANDOM_ASOF_TOP20_BACKTEST_EXECUTED: FALSE"
Write-Host "FORWARD_RETURNS_CREATED: FALSE"
Write-Host "BENCHMARK_RELATIVE_RETURNS_CREATED: FALSE"
Write-Host "OFFICIAL_RECOMMENDATION_CREATED: FALSE"
Write-Host "TRADING_SIGNAL_CREATED: FALSE"
Write-Host "BROKER_ORDER_EXECUTION_CODE_CREATED: FALSE"
Write-Host "OFFICIAL_RANKING_MUTATED: FALSE"
Write-Host "OFFICIAL_FACTOR_WEIGHTS_MUTATED: FALSE"
Write-Host "DYNAMIC_WEIGHTING_STARTED: FALSE"
Write-Host "PORTFOLIO_BACKTEST_CREATED: FALSE"
Write-Host "EQUITY_CURVE_CREATED: FALSE"
Write-Host "PERFORMANCE_CLAIMS_CREATED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_35_r1_historical_yahoo_cache_expansion_for_random_asof_backtest.py
