Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.7X"
Write-Host "PATCH_NAME: ACTIVE_MARKET_INPUT_LINEAGE_BINDING_RETRY_FROM_CERTIFIED_V20_7W_SOURCE"
Write-Host "REPORTING_ONLY: TRUE"
Write-Host "LINEAGE_BINDING_RETRY_ONLY: TRUE"
Write-Host "CREATES_NORMALIZED_ROWS: FALSE"
Write-Host "CREATES_FACTOR_EVIDENCE: FALSE"
Write-Host "CREATES_BACKTESTS: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING_ROWS: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"
Write-Host "V20_8_OUTPUTS_CREATED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_7x_active_market_input_lineage_binding_retry_from_certified_v20_7w_source.py
