Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.11"
Write-Host "PATCH_NAME: FACTOR_SOURCE_ATTACHMENT_PLAN_OR_FIRST_ATTACHABLE_FACTOR_LAYER"
Write-Host "REPORTING_ONLY: FALSE"
Write-Host "FACTOR_SOURCE_ATTACHMENT_PLAN_ONLY_OR_NON_SCORING_INPUT_LAYER: TRUE"
Write-Host "CREATES_FACTOR_SCORES: FALSE"
Write-Host "CREATES_FACTOR_EVIDENCE: FALSE"
Write-Host "CREATES_BACKTESTS: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING_ROWS: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_STRATEGY_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_11_factor_source_attachment_plan_or_first_attachable_factor_layer.py
