Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.15"
Write-Host "PATCH_NAME: FIRST_LIMITED_FACTOR_SCORE_LAYER"
Write-Host "REPORTING_ONLY: FALSE"
Write-Host "FIRST_LIMITED_FACTOR_SCORE_LAYER: TRUE"
Write-Host "CREATES_LIMITED_FACTOR_SCORES: TRUE"
Write-Host "CREATES_PERFORMANCE_METRICS: FALSE"
Write-Host "CREATES_FORWARD_RETURNS: FALSE"
Write-Host "CREATES_BENCHMARK_RELATIVE_RETURNS: FALSE"
Write-Host "CREATES_BACKTESTS: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING_ROWS: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_STRATEGY_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"
Write-Host "SOURCE_MUTATION_USED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_15_first_limited_factor_score_layer.py
