Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.36"
Write-Host "PATCH_NAME: ENTRY_STRATEGY_MATRIX_DESIGN"
Write-Host "DESIGN_ONLY: TRUE"
Write-Host "ENTRY_STRATEGY_BACKTEST_EXECUTED: FALSE"
Write-Host "RETURNS_CREATED: FALSE"
Write-Host "BENCHMARK_RELATIVE_RETURNS_CREATED: FALSE"
Write-Host "OFFICIAL_RECOMMENDATION_CREATED: FALSE"
Write-Host "TRADING_SIGNAL_CREATED: FALSE"
Write-Host "BROKER_ORDER_EXECUTION_CODE_CREATED: FALSE"
Write-Host "OFFICIAL_RANKING_MUTATED: FALSE"
Write-Host "OFFICIAL_FACTOR_WEIGHTS_MUTATED: FALSE"
Write-Host "DYNAMIC_WEIGHTING_STARTED: FALSE"
Write-Host "PORTFOLIO_BACKTEST_CREATED: FALSE"
Write-Host "EQUITY_CURVE_CREATED: FALSE"
Write-Host "PERFORMANCE_CLAIMS_CREATED: FALSE"
Write-Host "CURRENT_TOP20_USED_FOR_HISTORICAL_BACKTEST: FALSE"
Write-Host "NON_PIT_FACTORS_EXCLUDED: TRUE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_36_entry_strategy_matrix_design.py
