Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.16"
Write-Host "PATCH_NAME: FACTOR_SCORE_REVIEW_OR_BACKTEST_READINESS_GATE"
Write-Host "REPORTING_ONLY: FALSE"
Write-Host "FACTOR_SCORE_REVIEW_OR_BACKTEST_READINESS_GATE_ONLY: TRUE"
Write-Host "CREATES_FORWARD_RETURNS: FALSE"
Write-Host "CREATES_BENCHMARK_RELATIVE_RETURNS: FALSE"
Write-Host "CREATES_PERFORMANCE_METRICS: FALSE"
Write-Host "CREATES_BACKTESTS: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING_ROWS: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_STRATEGY_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"
Write-Host "SOURCE_MUTATION_USED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_16_factor_score_review_or_backtest_readiness_gate.py
