Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.10"
Write-Host "PATCH_NAME: FACTOR_SOURCE_ATTACHMENT_OR_AVAILABILITY_AUDIT"
Write-Host "REPORTING_ONLY: FALSE"
Write-Host "FACTOR_SOURCE_ATTACHMENT_AUDIT_ONLY: TRUE"
Write-Host "CREATES_FACTOR_SCORES: FALSE"
Write-Host "CREATES_FACTOR_EVIDENCE: FALSE"
Write-Host "CREATES_BACKTESTS: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING_ROWS: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_10_factor_source_attachment_or_availability_audit.py
