Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.34"
Write-Host "PATCH_NAME: EXTREME_RETURN_WARNING_TRIAGE_AND_RANDOM_BACKTEST_PREFLIGHT"
Write-Host "TRIAGE_ONLY: TRUE"
Write-Host "RANDOM_BACKTEST_PREFLIGHT_ONLY: TRUE"
Write-Host "OFFICIAL_RECOMMENDATION_CREATED: FALSE"
Write-Host "TRADING_SIGNAL_CREATED: FALSE"
Write-Host "BROKER_ORDER_EXECUTION_CODE_CREATED: FALSE"
Write-Host "OFFICIAL_RANKING_MUTATED: FALSE"
Write-Host "OFFICIAL_FACTOR_WEIGHTS_MUTATED: FALSE"
Write-Host "PORTFOLIO_BACKTEST_CREATED: FALSE"
Write-Host "EQUITY_CURVE_CREATED: FALSE"
Write-Host "PERFORMANCE_CLAIMS_CREATED: FALSE"
Write-Host "DYNAMIC_WEIGHTING_STARTED: FALSE"
Write-Host "RANDOM_ASOF_TOP20_BACKTEST_EXECUTED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_34_extreme_return_warning_triage_and_random_backtest_preflight.py
