Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.32"
Write-Host "PATCH_NAME: FIRST_LIMITED_BACKTEST_EXECUTION_RETRY_WITH_BASE_PRICES"
Write-Host "REPORTING_ONLY: TRUE"
Write-Host "FIRST_LIMITED_BACKTEST_EXECUTION_ONLY: TRUE"
Write-Host "EXPLORATORY_ONLY: TRUE"
Write-Host "OFFICIAL_BACKTEST: FALSE"
Write-Host "YAHOO_RUNTIME_REFRESH_EXECUTED: FALSE"
Write-Host "YFINANCE_OR_YAHOO_PROVIDER_USED_IN_THIS_STAGE: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"

python scripts/v20/v20_32_first_limited_backtest_execution_retry_with_base_prices.py
