Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.31"
Write-Host "PATCH_NAME: BASE_PRICE_ATTACHMENT_FOR_FIRST_LIMITED_BACKTEST"
Write-Host "REPORTING_ONLY: TRUE"
Write-Host "BASE_PRICE_ATTACHMENT_ONLY: TRUE"
Write-Host "YAHOO_RUNTIME_REFRESH_EXECUTED: FALSE"
Write-Host "YFINANCE_OR_YAHOO_PROVIDER_USED_IN_THIS_STAGE: FALSE"
Write-Host "CREATES_FORWARD_RETURNS: FALSE"
Write-Host "CREATES_BENCHMARK_RETURNS: FALSE"
Write-Host "CREATES_BENCHMARK_RELATIVE_RETURNS: FALSE"
Write-Host "CREATES_PERFORMANCE_METRICS: FALSE"
Write-Host "EXECUTES_BACKTESTS: FALSE"
Write-Host "CREATES_DYNAMIC_WEIGHTING: FALSE"
Write-Host "CREATES_TRADING_SIGNALS: FALSE"
Write-Host "CREATES_OFFICIAL_RECOMMENDATIONS: FALSE"
Write-Host "BROKER_API_USED: FALSE"
Write-Host "ORDER_EXECUTION_USED: FALSE"

python scripts/v20/v20_31_base_price_attachment_for_first_limited_backtest.py
