Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.35-R2"
Write-Host "PATCH_NAME: RANDOM_ASOF_TOP20_TECHNICAL_RECOMPUTE_BACKTEST_RETRY_FROM_HISTORICAL_CACHE"
Write-Host "EXPLORATORY_RESEARCH_ONLY: TRUE"
Write-Host "TECHNICAL_ONLY_RECOMPUTE: TRUE"
Write-Host "HISTORICAL_RANDOM_ASOF_CACHE_USED: TRUE"
Write-Host "CURRENT_TOP20_USED_FOR_HISTORICAL_BACKTEST: FALSE"
Write-Host "NON_PIT_FACTORS_EXCLUDED: TRUE"
Write-Host "OFFICIAL_RECOMMENDATION_CREATED: FALSE"
Write-Host "TRADING_SIGNAL_CREATED: FALSE"
Write-Host "BROKER_ORDER_EXECUTION_CODE_CREATED: FALSE"
Write-Host "OFFICIAL_RANKING_MUTATED: FALSE"
Write-Host "OFFICIAL_FACTOR_WEIGHTS_MUTATED: FALSE"
Write-Host "DYNAMIC_WEIGHTING_STARTED: FALSE"
Write-Host "PORTFOLIO_BACKTEST_CREATED: FALSE"
Write-Host "EQUITY_CURVE_CREATED: FALSE"
Write-Host "PERFORMANCE_CLAIMS_CREATED: FALSE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_35_r2_random_asof_top20_technical_recompute_backtest_retry_from_historical_cache.py
