Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "PATCH_VERSION: V20.39-R1"
Write-Host "PATCH_NAME: SHADOW_WEIGHTED_RECOMPUTE_BACKTEST"
Write-Host "SHADOW_ONLY: TRUE"
Write-Host "EXPLORATORY_RESEARCH_ONLY: TRUE"
Write-Host "OFFICIAL_FACTOR_WEIGHTS_MUTATED: FALSE"
Write-Host "OFFICIAL_RECOMMENDATION_CREATED: FALSE"
Write-Host "TRADING_SIGNAL_CREATED: FALSE"
Write-Host "BROKER_ORDER_EXECUTION_CODE_CREATED: FALSE"
Write-Host "OFFICIAL_RANKING_MUTATED: FALSE"
Write-Host "OFFICIAL_FACTOR_PROMOTION_CREATED: FALSE"
Write-Host "OFFICIAL_DYNAMIC_WEIGHTING_STARTED: FALSE"
Write-Host "PORTFOLIO_BACKTEST_CREATED: FALSE"
Write-Host "EQUITY_CURVE_CREATED: FALSE"
Write-Host "PERFORMANCE_CLAIMS_CREATED: FALSE"
Write-Host "CURRENT_TOP20_USED_FOR_HISTORICAL_BACKTEST: FALSE"
Write-Host "NON_PIT_FACTORS_EXCLUDED: TRUE"
Write-Host "V21_OUTPUTS_CREATED: FALSE"
Write-Host "V19_21_OUTPUTS_CREATED: FALSE"

python scripts/v20/v20_39_r1_shadow_weighted_recompute_backtest.py
