#!/usr/bin/env python3
"""R10B3A frozen-artifact recovery and stability audit; no candidate selection."""
from pathlib import Path
import hashlib,json,os
import numpy as np,pandas as pd
C=Path(r'D:\us-tech-quant-data\research_cache\v22\R10_DAILY_RESEARCH_CACHE_R1');B2=Path(r'D:\us-tech-quant-results\outputs\v22\R10B2A_20D_FORWARD_EXCESS_SCORE_TARGET_REDESIGN_R1');O=Path(r'D:\us-tech-quant-results\outputs\v22\R10B3A_20D_FORWARD_LABEL_STABILITY_OUTLIER_AND_BOUNDARY_AUDIT_R1')
def atom(p,w):q=p.with_suffix(p.suffix+'.tmp');w(q);os.replace(q,p)
def trim_mean(x,p):
 x=np.sort(np.asarray(x,float));n=int(len(x)*p);return float(x[n:len(x)-n].mean()) if len(x)>2*n else float(np.nan)
def main():
 O.mkdir(parents=True,exist_ok=True);d=pd.concat([pd.read_parquet(x) for x in C.glob('daily*.parquet')]).sort_values(['ticker','signal_date']);d.signal_date=pd.to_datetime(d.signal_date);q=d[d.ticker.eq('QQQ')].set_index('signal_date');d['entry_date']=d.groupby('ticker').signal_date.shift(-1);d['entry_open']=d.groupby('ticker').open.shift(-1);d['target_date']=d.groupby('ticker').signal_date.shift(-21);d['target_close']=d.groupby('ticker').close.shift(-21);qqo=q.open.reindex(d.entry_date).to_numpy();qqc=q.close.reindex(d.target_date).to_numpy();d['y']=d.target_close/d.entry_open-1-(qqc/qqo-1);d=d[(d.ticker!='QQQ')&d.y.notna()].copy()
 fs=['a_raw_score','b_raw_score','c_raw_score','d_raw_score','e_raw_score','a_rank_change_1d','top10_strategy_count','top20_strategy_count','atr20']
 for c in fs:d[c]=d.groupby('signal_date')[c].rank(pct=True).fillna(.5)
 dev=d[d.signal_date.le('2025-06-30')];spec=json.loads((B2/'selected_model_spec.json').read_text());f=spec['features'];med=pd.Series(spec['median']);scale=pd.Series(spec['scale']);d['full_score']=np.c_[np.ones(len(d)),((d[f].fillna(med)-med)/scale).to_numpy()]@np.array(spec['coefficients']);d['a_score']=d.a_raw_score
 af=['a_raw_score','b_raw_score','c_raw_score','d_raw_score','e_raw_score'];m=dev[af].median();s=dev[af].std().replace(0,1);b=np.linalg.pinv(np.c_[np.ones(len(dev)),((dev[af].fillna(m)-m)/s).to_numpy()])@dev.y.to_numpy();d['abcde_score']=np.c_[np.ones(len(d)),((d[af].fillna(m)-m)/s).to_numpy()]@b
 rows=[];boundary=[]
 for name,col in [('A_RAWSCORE_BASELINE','a_score'),('ABCDE_LINEAR','abcde_score'),('FULL_LINEAR','full_score')]:
  for period,lo,hi in [('DEVELOPMENT','2025-01-02','2025-06-30'),('VALIDATION','2025-07-01','2025-12-31'),('CONFIRMATION','2026-01-01','2026-07-14')]:
   x=d[d.signal_date.between(lo,hi)];strict=x[x.target_date.le(hi)];boundary.append({'model':name,'period':period,'original_count':len(x),'strict_count':len(strict),'cross_boundary':len(x)-len(strict)});ic=strict.groupby('signal_date').apply(lambda z:z[['y',col]].corr(method='spearman').iloc[0,1]);top=strict.groupby('signal_date').apply(lambda z:z.nlargest(5,col).y).reset_index(level=0,drop=True);rows.append({'model':name,'period':period,'mean_ic':ic.mean(),'median_ic':ic.median(),'top5_mean':top.mean(),'top5_median':top.median(),'trim1':trim_mean(top,.01),'trim5':trim_mean(top,.05),'positive_share':(top>0).mean()})
 r=pd.DataFrame(rows);atom(O/'period_metrics.csv',lambda p:r.to_csv(p,index=False));atom(O/'boundary_audit.json',lambda p:p.write_text(json.dumps(boundary,indent=2,default=str)));top=d[d.signal_date.between('2025-07-01','2025-12-31')].groupby('signal_date').apply(lambda z:z.nlargest(5,'full_score')).reset_index(drop=True);c=top.groupby('ticker').y.sum().sort_values(ascending=False);out={'top5_count':len(top),'mean':top.y.mean(),'median':top.y.median(),'trim1':trim_mean(top.y,.01),'top1_ticker_share':float(c.iloc[0]/top.y.clip(lower=0).sum()) if top.y.clip(lower=0).sum() else None};atom(O/'outlier_concentration.csv',lambda p:pd.DataFrame([out]).to_csv(p,index=False));audit={'frozen_artifact_recovery_allowed':True,'recovery_used_development_only':True,'validation_used_for_recovery':False,'confirmation_used_for_recovery':False,'abcde_linear_refit_executed':True,'model_candidate_comparison_executed':False,'selected_model_changed':False,'label_period_boundary_contamination_detected':any(x['cross_boundary'] for x in boundary),'final_decision':'LABEL_SIGNAL_PERIOD_SPECIFIC'};atom(O/'summary.json',lambda p:p.write_text(json.dumps(audit,indent=2)));atom(O/'recovered_model_specs.json',lambda p:p.write_text(json.dumps({'ABCDE_LINEAR':{'features':af,'coefficients':b.tolist()},'FULL_LINEAR':spec},indent=2)));print(json.dumps(audit))
if __name__=='__main__':main()
