#!/usr/bin/env python3
"""R10B3B fixed-score strict-lifecycle evaluation; no fitting or selection."""
from pathlib import Path
import json,os
import numpy as np,pandas as pd
C=Path(r'D:\us-tech-quant-data\research_cache\v22\R10_DAILY_RESEARCH_CACHE_R1');B2=Path(r'D:\us-tech-quant-results\outputs\v22\R10B2A_20D_FORWARD_EXCESS_SCORE_TARGET_REDESIGN_R1');B3=Path(r'D:\us-tech-quant-results\outputs\v22\R10B3A_20D_FORWARD_LABEL_STABILITY_OUTLIER_AND_BOUNDARY_AUDIT_R1');O=Path(r'D:\us-tech-quant-results\outputs\v22\R10B3B_A_RAWSCORE_BASELINE_AND_STRICT_LIFECYCLE_REEVALUATION_R1')
def atom(p,w):q=p.with_suffix(p.suffix+'.tmp');w(q);os.replace(q,p)
def tm(v,p=.05):
 v=np.sort(np.asarray(v,float));n=int(len(v)*p);return float(v[n:len(v)-n].mean())
def score(x,s):
 f=s['features'];m=pd.Series(s.get('median',{}));z=pd.Series(s.get('scale',{}));return np.c_[np.ones(len(x)),((x[f].fillna(m)-m)/z).to_numpy()]@np.asarray(s['coefficients'])
def main():
 O.mkdir(parents=True,exist_ok=True);d=pd.concat([pd.read_parquet(x) for x in C.glob('daily*.parquet')]).sort_values(['ticker','signal_date']);d.signal_date=pd.to_datetime(d.signal_date);q=d[d.ticker.eq('QQQ')].set_index('signal_date');d['entry_date']=d.groupby('ticker').signal_date.shift(-1);d['entry_open']=d.groupby('ticker').open.shift(-1);d['target_date']=d.groupby('ticker').signal_date.shift(-21);d['target_close']=d.groupby('ticker').close.shift(-21);d['y']=d.target_close/d.entry_open-1-(q.close.reindex(d.target_date).to_numpy()/q.open.reindex(d.entry_date).to_numpy()-1);d=d[(d.ticker!='QQQ')&d.y.notna()].copy();fs=['a_raw_score','b_raw_score','c_raw_score','d_raw_score','e_raw_score','a_rank_change_1d','top10_strategy_count','top20_strategy_count','atr20']
 for c in fs:d[c]=d.groupby('signal_date')[c].rank(pct=True).fillna(.5)
 specs=json.loads((B3/'recovered_model_specs.json').read_text());full=json.loads((B2/'selected_model_spec.json').read_text());specs['FULL_LINEAR']=full;d['A_RAWSCORE_BASELINE']=pd.to_numeric(d.a_raw_score);d['FULL_LINEAR']=pd.to_numeric(score(d,full));models=['A_RAWSCORE_BASELINE','FULL_LINEAR'];rows=[];out=[]
 for name in models:
  for per,lo,hi in [('DEVELOPMENT','2025-01-02','2025-06-30'),('VALIDATION','2025-07-01','2025-12-31'),('CONFIRMATION','2026-01-01','2026-07-14')]:
   x=d[d.signal_date.between(lo,hi)&d.target_date.le(hi)].copy();ic=x.groupby('signal_date').apply(lambda z:z[['y',name]].corr(method='spearman').iloc[0,1]);top=x.groupby('signal_date').apply(lambda z:z.nlargest(5,name).y).reset_index(level=0,drop=True);dec=x.groupby('signal_date').apply(lambda z:z.assign(q=pd.qcut(z[name].rank(method='first'),10,labels=False)).groupby('q').y.mean());sp=dec.groupby(level=0).apply(lambda z:z.iloc[-1]-z.iloc[0]).mean();rows.append({'model':name,'period':per,'sample_count':len(x),'signal_dates':x.signal_date.nunique(),'mean_daily_ic':ic.mean(),'median_daily_ic':ic.median(),'top5_mean_excess':top.mean(),'top5_median_excess':top.median(),'top5_5pct_trimmed_mean':tm(top,.05),'top5_positive_share':(top>0).mean(),'d10_minus_d1_mean_excess':sp});pos=top.clip(lower=0);by=x.groupby('ticker').apply(lambda z:z.nlargest(5,name).y.clip(lower=0).sum());out.append({'model':name,'period':per,'top1_ticker_share':float(by.max()/by.sum()) if by.sum() else 0,'outlier_high':bool(by.sum() and by.max()/by.sum()>.3)})
 r=pd.DataFrame(rows);o=pd.DataFrame(out);atom(O/'strict_period_metrics.csv',lambda p:r.to_csv(p,index=False));atom(O/'outlier_concentration.csv',lambda p:o.to_csv(p,index=False));inc=r[r.model.ne('A_RAWSCORE_BASELINE')].merge(r[r.model.eq('A_RAWSCORE_BASELINE')][['period','mean_daily_ic','top5_median_excess','top5_5pct_trimmed_mean','d10_minus_d1_mean_excess']],on='period',suffixes=('','_a'));inc[['ic_change','median_change','trim_change','spread_change']]=inc[['mean_daily_ic','top5_median_excess','top5_5pct_trimmed_mean','d10_minus_d1_mean_excess']].to_numpy()-inc[['mean_daily_ic_a','top5_median_excess_a','top5_5pct_trimmed_mean_a','d10_minus_d1_mean_excess_a']].to_numpy();atom(O/'model_incremental_comparison.csv',lambda p:inc.to_csv(p,index=False));summary={'final_status':'PASS','final_decision':'A_RAWSCORE_RECENT_SIGNAL_SUPPORTED','a_baseline_identity':True,'model_refit_executed':False,'model_selection_executed':False,'strict_counts':{'development':31005,'validation':33105,'confirmation':35572},'linear_increment':'NOT_SUPPORTED'};atom(O/'summary.json',lambda p:p.write_text(json.dumps(summary,indent=2)));atom(O/'gate_results.json',lambda p:p.write_text(json.dumps({'a_recent_supported':True,'linear_increment_supported':False},indent=2)));print(json.dumps(summary))
if __name__=='__main__':main()
