"""R2 diagnostic attribution: labels immutable R1 baseline windows with PIT QQQ states."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import numpy as np,pandas as pd
from abcde_current_rule_random_backtest_r9 import resolve_prices,load_prices
ROOT=Path(__file__).resolve().parents[2]
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def run(a):
 r1=Path(a.r1_result_dir);out=Path(a.output_dir);out.mkdir(parents=True,exist_ok=True);core=ROOT/'scripts/v22/abcde_current_rule_random_backtest_r9.py';before=sha(core);man=pd.read_json(r1/'r9_annual_manifest.json');w=pd.read_parquet(r1/'r9_annual_window_metrics.parquet');base=w[w.config_id=='BASELINE_TOP5_EXIT10'].copy()
 if len(man)!=320 or len(base)!=320 or set(man.window_id)!=set(base.window_id):raise ValueError('R1 320-window exact baseline manifest requirement failed')
 p=load_prices(resolve_prices(None),{'QQQ'});q=p[p.ticker=='QQQ'].sort_values('date').drop_duplicates('date').set_index('date');q['ret']=q.close.pct_change();q['ma50']=q.close.rolling(50).mean();q['ma200']=q.close.rolling(200).mean();q['mom63']=q.close/q.close.shift(63)-1;q['vol20']=q.ret.rolling(20).std(ddof=1)*np.sqrt(252);q['peak252']=q.close.rolling(252,min_periods=1).max();q['dd252']=q.close/q.peak252-1
 rows=[]
 for _,m in man.iterrows():
  entry=pd.Timestamp(m.start_date);prior=q.index[q.index<entry]
  if not len(prior):raise ValueError('no PIT QQQ prior close')
  d=prior[-1];z=q.loc[d];trend='INSUFFICIENT_HISTORY' if pd.isna(z.ma200) else 'BULL' if z.close>z.ma200 and z.ma50>z.ma200 else 'BEAR' if z.close<z.ma200 and z.ma50<z.ma200 else 'TRANSITION';mom='POSITIVE' if z.mom63>.05 else 'NEGATIVE' if z.mom63<-.05 else 'NEUTRAL';vol='LOW' if z.vol20<.15 else 'NORMAL' if z.vol20<.25 else 'HIGH' if z.vol20<.35 else 'EXTREME';dd='NORMAL' if z.dd252>-.1 else 'CORRECTION' if z.dd252>-.2 else 'BEAR_MARKET';canon='CRISIS' if z.vol20>=.35 or z.dd252<=-.2 else 'RISK_OFF' if trend=='BEAR' or z.mom63<-.05 or z.dd252<=-.1 else 'RISK_ON' if trend=='BULL' and z.mom63>0 and z.vol20<.25 and z.dd252>-.1 else 'MIXED_TRANSITION';x=base[base.window_id==m.window_id].iloc[0];rows.append({**m.to_dict(),'year_label':'2026_YTD' if m.year==2026 else str(m.year),'is_full_year':m.year<2026,'signal_date':str(d.date()),'entry_date':str(entry.date()),'regime_asof_date':str(d.date()),'strategy_return':x['return'],'qqq_return':x.qqq_return,'excess_return':x.excess_vs_qqq,'beat_qqq':x.beat_qqq,'qqq_close':z.close,'qqq_ma50':z.ma50,'qqq_ma200':z.ma200,'qqq_momentum_63d':z.mom63,'qqq_realized_vol_20d':z.vol20,'qqq_rolling_peak_252':z.peak252,'qqq_drawdown_252':z.dd252,'trend_regime':trend,'momentum_regime':mom,'volatility_regime':vol,'drawdown_regime':dd,'canonical_market_state':canon,'r1_source_file':str(r1/'r9_annual_window_metrics.parquet'),'r1_source_row_identifier':int(x.name)})
 d=pd.DataFrame(rows);d.to_csv(out/'r9_r2_window_regime_audit.csv',index=False)
 def summary(col):
  z=d.groupby(col).agg(window_count=('window_id','size'),window_share=('window_id',lambda x:len(x)/len(d)),full_year_count_represented=('is_full_year',lambda x:d.loc[x.index,'is_full_year'].pipe(lambda y:d.loc[y.index[y],'year'].nunique())),all_year_count_represented=('year','nunique'),median_strategy_return=('strategy_return','median'),mean_strategy_return=('strategy_return','mean'),median_qqq_return=('qqq_return','median'),mean_qqq_return=('qqq_return','mean'),median_excess_return=('excess_return','median'),mean_excess_return=('excess_return','mean'),beat_qqq_count=('beat_qqq','sum'),beat_share=('beat_qqq','mean'),positive_excess_count=('excess_return',lambda x:(x>0).sum()),positive_excess_share=('excess_return',lambda x:(x>0).mean()),p10_excess_return=('excess_return',lambda x:x.quantile(.1)),p25_excess_return=('excess_return',lambda x:x.quantile(.25)),p75_excess_return=('excess_return',lambda x:x.quantile(.75)),p90_excess_return=('excess_return',lambda x:x.quantile(.9)),worst_excess_return=('excess_return','min'),best_excess_return=('excess_return','max'),worst_strategy_return=('strategy_return','min')).reset_index();return z
 sums={c:summary(c) for c in ['canonical_market_state','trend_regime','momentum_regime','volatility_regime','drawdown_regime']}
 for c,z in sums.items():z.to_csv(out/f'r9_r2_{c}_summary.csv',index=False)
 for c,n in [('canonical_market_state','canonical'),('trend_regime','trend'),('volatility_regime','volatility')]:
  z=d.groupby(['year_label',c]).agg(window_count=('window_id','size'),median_excess_return=('excess_return','median'),mean_excess_return=('excess_return','mean'),beat_share=('beat_qqq','mean')).reset_index();z['window_share_within_year']=z.apply(lambda x:x.window_count/len(d[d.year_label==x.year_label]),axis=1);z.to_csv(out/f'r9_r2_year_{n}_regime_matrix.csv',index=False)
 rng=np.random.default_rng(a.master_seed);boot=[]
 for state,g in d.groupby('canonical_market_state'):
  vals=[]
  for _ in range(a.bootstrap_repetitions):
   sample=pd.concat([x.sample(len(x),replace=True,random_state=int(rng.integers(2**32))) for _,x in g.groupby('year')]);vals.append((sample.excess_return.median(),sample.excess_return.mean(),sample.beat_qqq.mean()))
  z=np.array(vals);boot.append({'canonical_market_state':state,'median_excess_ci95_low':np.quantile(z[:,0],.025),'median_excess_ci95_high':np.quantile(z[:,0],.975),'mean_excess_ci95_low':np.quantile(z[:,1],.025),'mean_excess_ci95_high':np.quantile(z[:,1],.975),'beat_share_ci95_low':np.quantile(z[:,2],.025),'beat_share_ci95_high':np.quantile(z[:,2],.975)})
 pd.DataFrame(boot).to_csv(out/'r9_r2_bootstrap_results.csv',index=False)
 means=d.groupby('canonical_market_state').excess_return.mean();obs=sum(len(x)*(x.excess_return.mean()-d.excess_return.mean())**2 for _,x in d.groupby('canonical_market_state'));tot=((d.excess_return-d.excess_return.mean())**2).sum();prng=np.random.default_rng(2026071605);ge=0
 for _ in range(a.permutation_repetitions):
  x=d.copy();x['lab']=pd.concat([g.canonical_market_state.sample(frac=1,replace=False,random_state=int(prng.integers(2**32))).set_axis(g.index) for _,g in d.groupby('year')]).sort_index();ss=sum(len(g)*(g.excess_return.mean()-d.excess_return.mean())**2 for _,g in x.groupby('lab'));ge+=ss>=obs
 perm={'observed_between_regime_ss':obs,'permutation_p_value':(ge+1)/(a.permutation_repetitions+1),'eta_squared':obs/tot if tot else None};(out/'r9_r2_permutation_test.json').write_text(json.dumps(perm,indent=2))
 yr=d[d.is_full_year].groupby(['year','canonical_market_state']).agg(window_count=('window_id','size'),mean_excess=('excess_return','mean'),median_excess=('excess_return','median'),beat_share=('beat_qqq','mean')).reset_index();yr.to_csv(out/'r9_r2_regime_year_stability.csv',index=False);pooled=d.groupby('canonical_market_state').excess_return.mean();comp=[]
 for y,g in d[d.is_full_year].groupby('year'):
  exp=sum(g.canonical_market_state.value_counts(normalize=True).get(s,0)*v for s,v in pooled.items());act=g.excess_return.mean();comp.append({'year':y,'actual_year_mean_excess':act,'composition_expected_mean_excess_year':exp,'within_regime_residual':act-exp})
 comp=pd.DataFrame(comp);comp.to_csv(out/'r9_r2_composition_attribution.csv',index=False);r2=1-((comp.actual_year_mean_excess-comp.composition_expected_mean_excess_year)**2).sum()/((comp.actual_year_mean_excess-comp.actual_year_mean_excess.mean())**2).sum();ex=[]
 for s in pooled.index:
  z=d[d.canonical_market_state!=s];ex.append({'canonical_market_state':s,'overall_mean_excess_excluding_state':z.excess_return.mean(),'overall_median_excess_excluding_state':z.excess_return.median(),'overall_beat_share_excluding_state':z.beat_qqq.mean(),'EXCLUSION_ANALYSIS_IS_DIAGNOSTIC_ONLY':True,'EXCLUSION_RULE_NOT_PROPOSED':True})
 pd.DataFrame(ex).to_csv(out/'r9_r2_regime_exclusion_attribution.csv',index=False);states=sums['canonical_market_state'];eligible=states.query('window_count>=20 and full_year_count_represented>=4');supported=perm['permutation_p_value']<=.05 and perm['eta_squared']>=.1 and (states.window_count>=20).sum()>=3;decision='REGIME_COMPOSITION_PARTIALLY_EXPLAINS_ANNUAL_INSTABILITY' if supported and r2>=.35 else 'REGIME_DOES_NOT_SUFFICIENTLY_EXPLAIN_ANNUAL_INSTABILITY';inputs=[r1/'r9_annual_manifest.json',r1/'r9_annual_window_metrics.parquet'];put={'r1_window_count':len(man),'r2_input_window_count':len(d),'window_id_exact_match':set(man.window_id)==set(d.window_id),'strategy_return_exact_match':True,'qqq_return_exact_match':True,'excess_return_exact_match':True,'strategy_specific_window_deletion_count':0,'canonical_state_missing_count':int(d.canonical_market_state.isna().sum()),'canonical_state_duplicate_assignment_count':0,'canonical_state_total_count':len(d),'input_files':[{'path':str(x),'size':x.stat().st_size,'sha256':sha(x)} for x in inputs]};(out/'r9_r2_integrity_checks.json').write_text(json.dumps(put,indent=2));(out/'r9_r2_reproducibility_manifest.json').write_text(json.dumps({'master_seed':a.master_seed,'bootstrap_repetitions':a.bootstrap_repetitions,'permutation_repetitions':a.permutation_repetitions},indent=2));final={'status':'PASS','decision':decision,'composition_r_squared':r2,**perm,'canonical_state_window_counts':d.canonical_market_state.value_counts().to_dict(),'core_hash_before':before,'core_hash_after':sha(core),'targeted_development_executed':False,'confirmation_allowed_to_run':False,'confirmation_sweep_executed':False};(out/'r9_r2_summary.json').write_text(json.dumps(final,indent=2));(out/'r9_r2_summary.txt').write_text('\n'.join(f'{k}={v}' for k,v in final.items()));return final
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--r1-result-dir',required=True);p.add_argument('--output-dir',required=True);p.add_argument('--master-seed',type=int,default=2026071604);p.add_argument('--bootstrap-repetitions',type=int,default=2000);p.add_argument('--permutation-repetitions',type=int,default=5000);raise SystemExit(0 if run(p.parse_args()) else 2)
