$ErrorActionPreference='Stop'
$root=(Resolve-Path "$PSScriptRoot\..\..").Path; Set-Location $root
$branch=git branch --show-current; if($branch -ne 'checkpoint/v22-078a-24h-event-entry-strategy-20260731'){throw "BRANCH_MISMATCH=$branch"}
if(-not (git log --format='%H' -1 dfff2fc)){throw 'BASELINE_V22_077A_MISSING'}
$changes=@(git status --short); $allowed=@('?? scripts/v22/v22_078a_fast3_24h_event_entry_strategy_r1.py','?? scripts/v22/test_v22_078a_fast3_24h_event_entry_strategy_r1.py','?? scripts/v22/run_v22_078a_fast3_24h_event_entry_strategy_r1.ps1'); if((Compare-Object $changes $allowed)){throw 'WORKTREE_NOT_CLEAN_OR_EXPECTED_NEW_FILES_ONLY'}
python -m py_compile scripts/v22/v22_078a_fast3_24h_event_entry_strategy_r1.py; $compile=$LASTEXITCODE
$tmp=Join-Path $env:TEMP 'v22_078a_pytest'; $collect=@(python -m pytest scripts/v22/test_v22_078a_fast3_24h_event_entry_strategy_r1.py --collect-only -q --basetemp $tmp 2>&1); $collectCode=$LASTEXITCODE; $collect | Write-Output; if($collectCode -ne 0){throw "TARGETED_TEST_COLLECTION_EXIT_CODE=$collectCode"}; $joined=$collect -join "`n"; if($joined -notmatch '(\d+) tests collected'){throw 'TARGETED_TEST_COUNT_UNAVAILABLE'}; $targetedCount=[int]$matches[1]; $pytest=@(python -m pytest scripts/v22/test_v22_078a_fast3_24h_event_entry_strategy_r1.py -q --basetemp $tmp 2>&1); $test=$LASTEXITCODE; $pytest | Write-Output; if($test -ne 0){throw "TARGETED_TEST_EXIT_CODE=$test"}; $pjoined=$pytest -join "`n"; if($pjoined -notmatch '(\d+) passed'){throw 'TARGETED_TEST_PASSED_COUNT_UNAVAILABLE'}; $targetedMatch=([int]$matches[1] -eq $targetedCount); if(-not $targetedMatch){throw "TARGETED_TEST_COUNT_MISMATCH collected=$targetedCount passed=$($matches[1])"}
python scripts/v22/v22_078a_fast3_24h_event_entry_strategy_r1.py; $run=$LASTEXITCODE; if($run -ne 0){throw "RUNNER_EXIT_CODE=$run"}
$out=Join-Path $root '.local_results/v22/V22.078A_FAST3_24H_EVENT_ENTRY_STRATEGY_R1'; $s=Get-Content (Join-Path $out 'v22_078a_summary.json') -Raw|ConvertFrom-Json
foreach($k in 'final_status','final_decision','research_trading_date_count','candidate_count','valid_fold_count','invalid_fold_count','time_order_violation_count','best_candidate','selected_signal_strategy','selected_exit_strategy','next_freeze_stage_allowed','fast3_24h_event_research_stopped','confirmation_remains_sealed','confirmation_row_read_count','model_fit_call_count','hyperparameter_search_count','final_frozen_model_output_count','data_leakage_detected','order_output_count'){"$($k.ToUpper())=$($s.$k)"}
"PYTHON_COMPILE_EXIT_CODE=$compile";"TARGETED_TEST_EXIT_CODE=$test";"TARGETED_TEST_COUNT=$targetedCount";"TARGETED_TEST_COUNT_MATCH=$targetedMatch";"RUNNER_EXIT_CODE=$run"
foreach($c in 'S1_E1','S1_E2','S2_E1','S2_E2','S3_E1','S3_E2'){foreach($k in 'trade_count','mean_net_return_at_25bps','profit_factor_at_25bps','maximum_drawdown_at_25bps'){"${c}_$($k.ToUpper())=$($s.($c+'_'+$k))"}}
foreach($k in 'trade_count','mean_net_return_at_10bps','mean_net_return_at_25bps','mean_net_return_at_50bps','median_net_return_at_25bps','profit_factor_at_25bps','positive_fold_ratio','positive_month_ratio','positive_year_ratio','maximum_drawdown_at_25bps','maximum_consecutive_losses','soxl_trade_count','soxl_mean_net_return_at_25bps','soxs_trade_count','soxs_mean_net_return_at_25bps','non_regular_entry_trade_count','non_regular_entry_mean_net_return_at_25bps'){"BEST_$($k.ToUpper())=$($s.($s.best_candidate+'_'+$k))"}
foreach($x in 'OVERNIGHT','PREMARKET','REGULAR','AFTER_HOURS'){$q=Import-Csv (Join-Path $out 'entry_session_scorecard.csv')|Where-Object {$_.candidate -eq $s.best_candidate -and $_.group -eq $x};"BEST_$($x)_ENTRY_COUNT=$($q.trade_count)";"BEST_$($x)_MEAN_NET_RETURN_AT_25BPS=$($q.mean_net_return_at_25bps)"}
"SUMMARY_PATH=$(Join-Path $out 'v22_078a_summary.json')";'NEW_FILE_LIST=scripts/v22/v22_078a_fast3_24h_event_entry_strategy_r1.py,scripts/v22/test_v22_078a_fast3_24h_event_entry_strategy_r1.py,scripts/v22/run_v22_078a_fast3_24h_event_entry_strategy_r1.ps1';'GIT_STATUS_SHORT=';git status --short
