param([switch]$Execute, [string]$UpstreamResultsRoot = ".\.local_results", [string]$ResultsRoot = ".\.local_results")
$ErrorActionPreference='Stop'; $repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path; $python=Join-Path $repo '.venv\Scripts\python.exe'; $script=Join-Path $repo 'scripts\v22\v22_069c_fast3_nonlinear_compact_validation_r1.py'; $test=Join-Path $repo 'scripts\v22\test_v22_069c_fast3_nonlinear_compact_validation_r1.py'
if((git -C $repo branch --show-current).Trim() -ne 'checkpoint/v22-069c-validation-20260731'){throw 'BRANCH_MISMATCH'}
& $python -m py_compile $script; $compile=$LASTEXITCODE; if($compile -ne 0){exit $compile}; & $python -m pytest $test -q; $tests=$LASTEXITCODE; if($tests -ne 0){exit $tests}
if(-not $Execute){exit 0}
& $python $script --execute --upstream-results-root (Join-Path $repo $UpstreamResultsRoot) --results-root (Join-Path $repo $ResultsRoot); if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
$out=Join-Path (Join-Path (Join-Path $repo $ResultsRoot) 'v22') 'V22.069C_FAST3_NONLINEAR_COMPACT_VALIDATION_R1'; $summaryPath=Join-Path $out 'v22_069c_summary.json'; $s=Get-Content -Raw $summaryPath|ConvertFrom-Json
git -C $repo diff --check; if($LASTEXITCODE -ne 0){exit 1}
foreach($key in 'final_status','final_decision','validation_event_count','validation_row_read_count','development_training_row_read_count','confirmation_row_read_count','fit_call_count','hyperparameter_search_count','model_artifact_sha256','model_state_sha256','eligible_for_v22_069d','order_output_count','position_output_count','broker_connection_count'){"$($key.ToUpper())=$($s.$key)"}; "PYTHON_COMPILE_EXIT_CODE=$compile"; "TARGETED_TEST_EXIT_CODE=$tests"; "TARGETED_TEST_COUNT=5"; "SUMMARY_PATH=$summaryPath"
if($s.final_status -ne 'PASS' -or $s.validation_event_count -le 0 -or $s.validation_row_read_count -le 0 -or $s.development_training_row_read_count -ne 0 -or $s.confirmation_row_read_count -ne 0 -or $s.fit_call_count -ne 0 -or $s.hyperparameter_search_count -ne 0 -or $s.order_output_count -ne 0 -or $s.broker_connection_count -ne 0){exit 1}
