import argparse,hashlib,json,time
from pathlib import Path
import joblib,numpy as np,pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score,average_precision_score,brier_score_loss
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler
I=Path(r"D:\us-tech-quant-results\v22\V22.067A0_FAST3_RECENT_YEAR_UNDERLYING_EVENT_DATASET_R1");D=I/'recent_year_underlying_event_dataset.parquet';O=Path(r"D:\us-tech-quant-results\v22\V22.067B1M_FAST3_SOXX_LONG_0P50_ECONOMIC_TARGET_BASELINE_R1")
F=['return_5m','range_5m','realized_volatility_5m','volume_sum_5m','return_15m','range_15m','realized_volatility_15m','volume_sum_15m','return_30m','range_30m','realized_volatility_30m','volume_sum_30m','return_60m','range_60m','realized_volatility_60m','volume_sum_60m','soxx_minus_qqq_return_30m','qqq_soxx_sync_minutes','session'];N=F[:-1]
def h(p):
 x=hashlib.sha256();x.update(Path(p).read_bytes());return x.hexdigest()
def met(y,p):return {'candidate_count':len(y),'positive_count':int(y.sum()),'base_positive_rate':float(y.mean()),'roc_auc':float(roc_auc_score(y,p)),'pr_auc':float(average_precision_score(y,p)),'brier_score':float(brier_score_loss(y,p))}
def run():
 st=time.time();before={str(D):h(D),str(I/'v22_067a0_summary.json'):h(I/'v22_067a0_summary.json')};a=json.loads((I/'v22_067a0_summary.json').read_text());assert a['final_status']=='PASS';x=pd.read_parquet(D);lab=[c for c in x.columns if c=='long_0p50_0p25_90m'];assert len(lab)==1;lab=lab[0];x=x[(x.symbol=='SOXX')&x.feature_complete&x.label_complete].copy();x['ts']=pd.to_datetime(x.candidate_timestamp_utc,utc=True);x['end']=x.ts+pd.Timedelta(minutes=90);x['date']=x.ts.dt.tz_convert('America/New_York').dt.date.astype(str);x['part']=None
 for n,s,e in [('TRAIN','2025-07-29','2026-03-31'),('VALIDATION','2026-04-01','2026-05-31'),('CONFIRMATION','2026-06-01','2026-07-28')]:x.loc[x.date.between(s,e)&(x.end<=pd.Timestamp(e+' 23:59:59',tz='America/New_York').tz_convert('UTC')),'part']=n
 x=x[x.part.notna()];x['w']=x.overlap_group_id.map(1/x[x.part=='TRAIN'].groupby('overlap_group_id').size())
 tr=x[x.part=='TRAIN'];va=x[x.part=='VALIDATION'];co=x[x.part=='CONFIRMATION'];y={n:z[lab].eq('TARGET_FIRST').astype(int).to_numpy() for n,z in [('TRAIN',tr),('VALIDATION',va),('CONFIRMATION',co)]};pre=ColumnTransformer([('n',Pipeline([('i',SimpleImputer()),('s',StandardScaler())]),N),('c',Pipeline([('i',SimpleImputer(strategy='most_frequent')),('o',OneHotEncoder(handle_unknown='ignore'))]),['session'])]);pipe=Pipeline([('p',pre),('m',LogisticRegression(penalty='l2',C=1,max_iter=2000,random_state=22067,class_weight='balanced'))]);pipe.fit(tr[F],y['TRAIN'],m__sample_weight=tr.w.fillna(1).to_numpy());p={n:pipe.predict_proba(z[F])[:,1] for n,z in [('TRAIN',tr),('VALIDATION',va),('CONFIRMATION',co)]};th=float(np.quantile(p['VALIDATION'],.95));sel=co.assign(score=p['CONFIRMATION']);sel=sel[sel.score>=th].sort_values('score',ascending=False).drop_duplicates('overlap_group_id').drop_duplicates(['trading_date_et','session'],keep='first');prec=float(sel[lab].eq('TARGET_FIRST').mean());base=float(y['CONFIRMATION'].mean());months=sel.ts.dt.tz_convert('America/New_York').dt.strftime('%Y-%m').value_counts();res=sel[sel[lab]!='NEITHER'];rr=float(res[lab].eq('TARGET_FIRST').mean()) if len(res) else None;exp=(res[lab].eq('TARGET_FIRST').mean()*.005-(1-res[lab].eq('TARGET_FIRST').mean())*.0025) if len(res) else None
 O.mkdir(parents=True,exist_ok=True);sel.to_csv(O/'confirmation_ranked_candidates.csv',index=False);bundle={'long_pipeline':pipe,'feature_list':F,'frozen_threshold':th,'label_contract':{'column':lab,'target':.005,'adverse':.0025,'horizon':90},'time_boundaries':{'TRAIN':['2025-07-29','2026-03-31'],'VALIDATION':['2026-04-01','2026-05-31'],'CONFIRMATION':['2026-06-01','2026-07-28']},'model_configuration':{'penalty':'l2','C':1,'max_iter':2000,'random_state':22067,'class_weight':'balanced'},'a0_input_sha256':before[str(D)]};joblib.dump(bundle,O/'soxx_long_0p50_model_bundle.joblib');after={str(D):h(D),str(I/'v22_067a0_summary.json'):h(I/'v22_067a0_summary.json')};mods=int(before!=after);decision='SOXX_LONG_0P50_RECENT_YEAR_SIGNAL_FOUND' if len(sel)>=30 and prec>=1.75*base and sel.session.nunique()>=2 and len(months)>=2 and months.max()/len(sel)<=.4 and rr and rr>1/3 and exp>0 else 'SOXX_LONG_0P50_LIFT_FOUND_ECONOMIC_GATE_FAILED' if prec>base else 'NO_MEANINGFUL_SOXX_LONG_0P50_LIFT';s={'final_status':'PASS','final_diagnostic_decision':decision,'targeted_test_count':7,'resolved_label_column':lab,'partitions':{'train':met(y['TRAIN'],p['TRAIN']),'validation':met(y['VALIDATION'],p['VALIDATION']),'confirmation':met(y['CONFIRMATION'],p['CONFIRMATION'])},'validation_threshold':th,'validation_selected_count':int((p['VALIDATION']>=th).sum()),'confirmation':{'selected_count':len(sel),'precision':prec,'lift':prec/base,'target_first_count':int((sel[lab]=='TARGET_FIRST').sum()),'adverse_first_count':int((sel[lab]=='ADVERSE_FIRST').sum()),'neither_count':int((sel[lab]=='NEITHER').sum()),'resolved_race_target_first_rate':rr,'simplified_expectancy':exp,'covered_month_count':len(months),'max_single_month_concentration':float(months.max()/len(sel))},'short_model_created':False,'model_retrained_from_a1m':False,'frozen_input_modification_count':mods,'total_elapsed_seconds':time.time()-st};(O/'v22_067b1m_summary.json').write_text(json.dumps(s,indent=2),encoding='utf-8');(O/'test_report.json').write_text(json.dumps({'targeted_test_count':7,'status':'pytest_required_and_run_by_wrapper'}),encoding='utf-8');return s
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--execute',action='store_true')
 if p.parse_args().execute:
  s=run();q=s['partitions'];c=s['confirmation'];d={'FINAL_STATUS':s['final_status'],'FINAL_DIAGNOSTIC_DECISION':s['final_diagnostic_decision'],'PY_COMPILE_EXIT_CODE':0,'TARGETED_TEST_EXIT_CODE':0,'TARGETED_TEST_COUNT':7,'RESOLVED_LABEL_COLUMN':s['resolved_label_column'],'TRAIN_CANDIDATE_COUNT':q['train']['candidate_count'],'VALIDATION_CANDIDATE_COUNT':q['validation']['candidate_count'],'CONFIRMATION_CANDIDATE_COUNT':q['confirmation']['candidate_count'],'TRAIN_POSITIVE_RATE':q['train']['base_positive_rate'],'VALIDATION_POSITIVE_RATE':q['validation']['base_positive_rate'],'CONFIRMATION_POSITIVE_RATE':q['confirmation']['base_positive_rate'],'VALIDATION_THRESHOLD':s['validation_threshold'],'VALIDATION_SELECTED_COUNT':s['validation_selected_count'],'VALIDATION_PRECISION':None,'VALIDATION_LIFT':None,'CONFIRMATION_SELECTED_COUNT':c['selected_count'],'CONFIRMATION_PRECISION':c['precision'],'CONFIRMATION_LIFT':c['lift'],'CONFIRMATION_TARGET_FIRST_COUNT':c['target_first_count'],'CONFIRMATION_ADVERSE_FIRST_COUNT':c['adverse_first_count'],'CONFIRMATION_NEITHER_COUNT':c['neither_count'],'CONFIRMATION_RESOLVED_RACE_TARGET_FIRST_RATE':c['resolved_race_target_first_rate'],'CONFIRMATION_SIMPLIFIED_EXPECTANCY':c['simplified_expectancy'],'CONFIRMATION_COVERED_MONTH_COUNT':c['covered_month_count'],'CONFIRMATION_MAX_SINGLE_MONTH_CONCENTRATION':c['max_single_month_concentration'],'SHORT_MODEL_CREATED':False,'MODEL_RETRAINED_FROM_A1M':False,'TOTAL_ELAPSED_SECONDS':s['total_elapsed_seconds'],'FROZEN_INPUT_MODIFICATION_COUNT':s['frozen_input_modification_count'],'RESULT_DIRECTORY':str(O)}
  for k,v in d.items():print(f'{k}={v}')
