from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
import pandas as pd
OUT=Path(r'D:\us-tech-quant-results\v22\V22.066IA0_FAST3_FROZEN_LEDGER_MAPPING_AUDIT_R1');PROV=Path(r'D:\us-tech-quant-results\v22\V22.066H_FAST3_HISTORICAL_CANDIDATE_TRADE_PATH_ATLAS_R1\historical_input_provenance.json')
REQ=['trade_id','signal_timestamp_utc','entry_timestamp_utc','exit_timestamp_utc','direction','selected_instrument','execution_symbol','study_period','gap_regime','included']; MAP={'TQQQ':('QQQ','LONG','TQQQ_TO_QQQ_LONG'),'SQQQ':('QQQ','SHORT','SQQQ_TO_QQQ_SHORT'),'SOXL':('SOXX','LONG','SOXL_TO_SOXX_LONG'),'SOXS':('SOXX','SHORT','SOXS_TO_SOXX_SHORT')}
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def norm(x):return str(x).upper().replace('US.','').strip()
def dnorm(x):return 'LONG' if str(x).upper() in ['LONG','BUY','UP','1','+1'] else 'SHORT' if str(x).upper() in ['SHORT','SELL','DOWN','-1'] else None
def run():
 OUT.mkdir(parents=True,exist_ok=True);p=json.loads(PROV.read_text());src=Path(p['selected_source_file']);before=h(src);t=pd.read_csv(src);assert set(REQ)<=set(t)
 atom={'provenance_path':str(PROV),'source_path':str(src),'recorded_hash':p['source_file_hash'],'actual_hash':before,'recorded_row_count':p['row_count'],'actual_row_count':len(t),'verified':before==p['source_file_hash'] and len(t)==p['row_count']};(OUT/'historical_input_provenance_verified.json').write_text(json.dumps(atom,indent=2))
 audit=pd.DataFrame([{'column_name':c,'dtype':str(t[c].dtype),'row_count':len(t),'non_null_count':t[c].notna().sum(),'null_count':t[c].isna().sum(),'unique_count':t[c].nunique(),'example_value':str(t[c].dropna().iloc[0]) if t[c].notna().any() else '','is_key':c in REQ,'audit_status':'PASS'} for c in t]);audit.to_csv(OUT/'ledger_schema_audit.csv',index=False)
 rows=[]
 for _,r in t.iterrows():
  e=norm(r.execution_symbol); sel=norm(r.selected_instrument); m=MAP.get(e); nd=dnorm(r.direction); issues=[]
  if not m:issues+=['UNKNOWN_EXECUTION_SYMBOL'];u=ex=rule=None;resolved=False
  else:u,ex,rule=m;resolved=True;issues+=[] if nd==ex else ['DIRECTION_EXECUTION_SYMBOL_CONFLICT'];issues+=[] if sel==e else ['SELECTED_EXECUTION_SYMBOL_MISMATCH']
  ts=[pd.to_datetime(r[x],utc=True,errors='coerce') for x in ['signal_timestamp_utc','entry_timestamp_utc','exit_timestamp_utc']]
  if any(pd.isna(x) for x in ts) or not(ts[0]<=ts[1]<=ts[2]):issues+=['TIMESTAMP_ORDER_INVALID']
  rows.append({'trade_id':r.trade_id,'signal_timestamp_utc':r.signal_timestamp_utc,'entry_timestamp_utc':r.entry_timestamp_utc,'exit_timestamp_utc':r.exit_timestamp_utc,'original_direction':r.direction,'normalized_direction':nd,'selected_instrument':r.selected_instrument,'execution_symbol_original':r.execution_symbol,'execution_symbol_normalized':e,'underlying_symbol':u,'expected_direction_from_execution_symbol':ex,'direction_consistent':nd==ex,'mapping_resolved':resolved,'mapping_rule_id':rule,'mapping_issue_code':'|'.join(issues),'study_period':r.study_period,'gap_regime':r.gap_regime,'included':r.included})
 x=pd.DataFrame(rows);x.to_csv(OUT/'underlying_trade_mapping.csv',index=False);x[x.mapping_issue_code.ne('')].to_csv(OUT/'mapping_issues.csv',index=False);pd.DataFrame([{'rule':k,'underlying':v[0],'direction':v[1]} for k,v in MAP.items()]).to_json(OUT/'mapping_rules.json',orient='records');t.groupby(['study_period','gap_regime'],dropna=False).size().reset_index(name='count').to_csv(OUT/'period_subgroup_counts.csv',index=False)
 (OUT/'ledger_field_mapping.json').write_text(json.dumps({k:k for k in REQ},indent=2));after=h(src);s={'final_status':'PASS','final_diagnostic_decision':'FROZEN_LEDGER_MAPPING_READY','historical_base_trade_count':len(t),'mapping_processed_trade_count':len(x),'mapping_resolved_count':int(x.mapping_resolved.sum()),'mapping_unresolved_count':int((~x.mapping_resolved).sum()),'direction_conflict_count':int(x.mapping_issue_code.str.contains('DIRECTION').sum()),'selected_instrument_conflict_count':int(x.mapping_issue_code.str.contains('SELECTED').sum()),'timestamp_issue_count':int(x.mapping_issue_code.str.contains('TIMESTAMP').sum()),'duplicate_trade_id_count':int(x.trade_id.duplicated().sum()),'qqq_mapped_trade_count':int(x.underlying_symbol.eq('QQQ').sum()),'soxx_mapped_trade_count':int(x.underlying_symbol.eq('SOXX').sum()),'tqqq_execution_count':int(x.execution_symbol_normalized.eq('TQQQ').sum()),'sqqq_execution_count':int(x.execution_symbol_normalized.eq('SQQQ').sum()),'soxl_execution_count':int(x.execution_symbol_normalized.eq('SOXL').sum()),'soxs_execution_count':int(x.execution_symbol_normalized.eq('SOXS').sum()),'source_trade_count':int(t.study_period.eq('2018-2022_DEVELOPMENT').sum()),'validation_trade_count':int(t.study_period.eq('2023-2024_VALIDATION').sum()),'confirmation_trade_count':int(t.study_period.eq('2025-2026_YTD_CONFIRMATION').sum()),'frozen_input_modification_count':int(before!=after),'broker_action_allowed':False,'paper_action_allowed':False,'official_adoption_allowed':False};(OUT/'v22_066ia0_summary.json').write_text(json.dumps(s,indent=2));(OUT/'test_report.json').write_text('{}');return s
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--execute',action='store_true');z=a.parse_args();s=run() if z.execute else {};[print(f'{k.upper()}={v}') for k,v in s.items()]
