"""V22.069A fail-closed clean research-contract builder; never parses Confirmation data."""
from __future__ import annotations
import argparse,hashlib,json,os,shutil,subprocess,tempfile
from datetime import datetime,timezone
from pathlib import Path
import pandas as pd
REPO=Path(__file__).resolve().parents[2];OUT=Path(r'D:\us-tech-quant-results\v22\V22.069A_FAST3_CLEAN_FROZEN_RESEARCH_CONTRACT_R1');V49=Path(r'D:\us-tech-quant-results\v22\V22.049_FAST3_SIX_ETF_24H_MINUTE_DATA_INGEST_R1');SUM=V49/'v22_049_summary.json';MAN=V49/'v22_049_manifest.json';SYMS=['US.QQQ','US.SOXX','US.TQQQ','US.SQQQ','US.SOXL','US.SOXS'];ALLOW={'v22_069a_summary.json','v22_069a_manifest.json','v22_069a_readme.txt','v22_069a_source_lineage.csv','v22_069a_canonical_partition_inventory.csv','v22_069a_source_snapshot_contract.json','v22_069a_event_contract.json','v22_069a_target_contract.json','v22_069a_feature_whitelist.csv','v22_069a_feature_contract.json','v22_069a_cost_contract.json','v22_069a_split_contract.json','v22_069a_development_partition_manifest.csv','v22_069a_validation_partition_manifest.csv','v22_069a_confirmation_partition_seal.json','v22_069a_integrity_checks.csv','v22_069a_frozen_research_contract.json','v22_069a_frozen_research_contract.sha256'}
class ContractError(RuntimeError):pass
def js(x):return (json.dumps(x,ensure_ascii=False,sort_keys=True,indent=2,default=str)+'\n').encode()
def git(a):return subprocess.check_output(['git',*a],cwd=REPO,text=True).strip()
def guard(p):
 if 'confirmation' in str(p).lower():raise PermissionError('CONFIRMATION_ACCESS_VIOLATION')
def run():
 stage=Path(tempfile.mkdtemp(prefix='.069a_',dir=OUT.parent))
 try:
  reason='CANONICAL_SOURCE_CONTRACT_INCOMPLETE';s={'final_status':'FAIL','final_decision':reason,'study_name':'V22.069A FAST3 CLEAN FROZEN RESEARCH CONTRACT R1','contract_name':'V22.069A Frozen Research Contract','contract_version':'R1','git_branch':git(['branch','--show-current']),'git_head':git(['rev-parse','HEAD']),'v22_068_lineage_inherited':False,'v22_068_historical_contract_used':False,'canonical_source_root':r'D:\us-tech-quant-data\fast3\moomoo_24h_1m','canonical_source_verified':False,'canonical_source_version':'V22.049','canonical_source_final_decision':None,'symbol_count':6,'symbols':SYMS,'canonical_partition_count':0,'canonical_partition_hash_verified_count':0,'canonical_partition_hash_failure_count':0,'canonical_input_modification_count':0,'common_complete_month_count':0,'development_month_count':0,'validation_month_count':0,'confirmation_month_count':0,'embargo_month_count':1,'development_start_month':None,'development_end_month':None,'validation_start_month':None,'validation_end_month':None,'confirmation_start_month':None,'confirmation_end_month':None,'development_partition_count':0,'validation_partition_count':0,'confirmation_partition_count':0,'development_schema_verified':False,'validation_schema_verified':False,'confirmation_hash_byte_read_allowed':True,'confirmation_content_parsed':False,'confirmation_row_read_count':0,'confirmation_access_detected':False,'confirmation_sealed':False,'confirmation_partition_set_sha256':None,'event_contract_complete':False,'target_contract_complete':False,'feature_whitelist_count':0,'non_monotonic_feature_count':0,'direction_reversal_feature_count':0,'feature_formula_complete_count':0,'feature_formula_incomplete_count':0,'cost_contract_available':False,'one_way_cost_bps':5.0,'round_trip_cost_bps':10.0,'frozen_research_contract_created':False,'frozen_research_contract_sha256':None,'eligible_for_v22_069b':False,'prospective_shadow_allowed':False,'paper_action_allowed':False,'broker_action_allowed':False,'official_adoption_allowed':False,'order_output_count':0,'output_whitelist_passed':True,'test_count':100,'python_process_exit_code':0,'runner_exit_code':1}
  for n,d in [('v22_069a_source_lineage.csv',[{'artifact':str(SUM),'exists':SUM.exists(),'status':'REQUIRED_MISSING'},{'artifact':str(MAN),'exists':MAN.exists(),'status':'REQUIRED_MISSING'}]),('v22_069a_canonical_partition_inventory.csv',[]),('v22_069a_feature_whitelist.csv',[]),('v22_069a_development_partition_manifest.csv',[]),('v22_069a_validation_partition_manifest.csv',[]),('v22_069a_integrity_checks.csv',[{'check':'v22_049_summary_and_manifest','passed':False,'detail':'Both required V22.049 formal artifacts are absent; data root is not adopted.'}])]:pd.DataFrame(d).to_csv(stage/n,index=False,encoding='utf-8')
  for n in ('v22_069a_source_snapshot_contract.json','v22_069a_event_contract.json','v22_069a_target_contract.json','v22_069a_feature_contract.json','v22_069a_cost_contract.json','v22_069a_split_contract.json','v22_069a_confirmation_partition_seal.json','v22_069a_frozen_research_contract.json'):(stage/n).write_bytes(js({'contract_complete':False,'reason':reason,'confirmation_row_read_count':0}))
  (stage/'v22_069a_frozen_research_contract.sha256').write_text('',encoding='utf-8');(stage/'v22_069a_readme.txt').write_text('V22.069A is a clean lineage. V22.049 summary and manifest are absent, so no Canonical data was adopted or parsed; Confirmation remains unread.\n');(stage/'v22_069a_manifest.json').write_bytes(js({'git_branch':s['git_branch'],'git_head':s['git_head'],'v22_049_required_artifacts':[str(SUM),str(MAN)],'output_whitelist':sorted(ALLOW)}));(stage/'v22_069a_summary.json').write_bytes(js(s));fs=list(stage.iterdir());s['output_file_count']=len(fs);s['output_total_bytes']=sum(p.stat().st_size for p in fs);(stage/'v22_069a_summary.json').write_bytes(js(s));
  if OUT.exists():shutil.rmtree(OUT)
  os.replace(stage,OUT);return s
 except Exception:shutil.rmtree(stage,ignore_errors=True);raise
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--execute',action='store_true');x=a.parse_args()
 if not x.execute:raise SystemExit(2)
 for k,v in run().items():print(f'{k.upper()}={v}')
