"""Version the retained V21.233 compact output without changing its formula."""
from __future__ import annotations
import hashlib,json,os
from pathlib import Path
from datetime import datetime,timezone
import pandas as pd
ROOT=Path(r'D:\us-tech-quant'); SRC=Path(r'D:\us-tech-quant-daily\current\V21.233_MOOMOO_ONLY_ABCDE_RERUN\abcde_strategy_ranking_master.csv')
CODE=ROOT/'scripts/v21/v21_233_moomoo_only_abcde_rerun.py'; CAN=Path(r'D:\us-tech-quant-data\canonical\v22\ABCDE_COMPACT_V1_DAILY_HISTORY_R1'); LEG=Path(r'D:\us-tech-quant-data\canonical\v22\REAL_ABCDE_DAILY_HISTORY_R1'); OUT=Path(r'D:\us-tech-quant-results\outputs\v22\V22_050_COMPACT_ABCDE_PRODUCTION_VERSIONING_AND_FORWARD_LEDGER_R1')
def h(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def wj(x,p):p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(x,indent=2,default=str),encoding='utf8');os.replace(t,p)
def wp(x,p):p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix('.parquet.tmp');x.to_parquet(t,index=False);os.replace(t,p)
def run():
 x=pd.read_csv(SRC); x['signal_date']=pd.to_datetime(x.latest_date).dt.normalize(); code=h(CODE); cfg=hashlib.sha256(CODE.read_text(encoding='utf8').split('RANK_FIELDS')[0].encode()).hexdigest(); sf=h(SRC)
 x=x.rename(columns={'strategy_name':'strategy_name','score':'raw_score'});x['universe_size']=x.groupby(['signal_date','strategy_name']).ticker.transform('size');x['model_family']='ABCDE_COMPACT';x['model_version']='ABCDE_COMPACT_V1';x['producer_name']='V21.233_COMPACT_RANKING_PRODUCER';x['producer_code_fingerprint']=code;x['strategy_config_fingerprint']=cfg;x['feature_schema_fingerprint']=hashlib.sha256('momentum|trend|volatility|drawdown|liquidity|data_trust'.encode()).hexdigest();x['source_policy']='MOOMOO_ONLY';x['compact_proxy_used']=True;x['price_only_proxy_used']=True;x['legacy_abcde_equivalent']=False;x['forward_research_eligible']=True;x['source_run_id']=x.source_snapshot_id;x['source_summary_path']='';x['source_snapshot_path']=str(SRC);x['source_snapshot_fingerprint']=sf;x['ranking_integrity_pass']=True;x['same_date_comparable']=True;x['source_final_status']='PASS_V22_044_DAILY_SINGLE_ENTRYPOINT_FROZEN';x['persisted_at']=datetime.now(timezone.utc).isoformat();x['schema_version']='ABCDE_COMPACT_V1_DAILY_HISTORY_R1'
 cols=['signal_date','strategy_name','ticker','raw_score','rank','universe_size','model_family','model_version','producer_name','producer_code_fingerprint','strategy_config_fingerprint','feature_schema_fingerprint','source_policy','compact_proxy_used','price_only_proxy_used','legacy_abcde_equivalent','forward_research_eligible','source_run_id','source_summary_path','source_snapshot_path','source_snapshot_fingerprint','ranking_integrity_pass','same_date_comparable','source_final_status','persisted_at','schema_version'];x=x[cols]
 p=CAN/'abcde_compact_v1_daily_2026.parquet';old=pd.read_parquet(p) if p.exists() else x.iloc[0:0];key=['signal_date','model_version','strategy_name','ticker'];both=old.merge(x,on=key,suffixes=('_o','_n'));conf=int(((both.raw_score_o-both.raw_score_n).abs()>1e-12).sum()) if len(both) else 0
 if conf: raise RuntimeError('COMPACT_HISTORY_IMMUTABILITY_CONFLICT')
 new=x.merge(old[key],on=key,how='left',indicator=True).query("_merge=='left_only'").drop(columns='_merge');allx=pd.concat([old,new],ignore_index=True).drop_duplicates(key,keep='first').sort_values(key);wp(allx,p)
 spec={'model_family':'ABCDE_COMPACT','model_version':'ABCDE_COMPACT_V1','producer_script':str(CODE),'producer_function':'build_rankings','strategy_names':sorted(x.strategy_name.unique()),'feature_names_by_strategy':{s:['momentum','trend','volatility','drawdown','liquidity','data_trust'] for s in x.strategy_name.unique()},'score_direction':'higher_is_better','ranking_direction':'descending','normalization_rules':'cross-sectional pct_rank','missing_value_rules':'exclude insufficient history','weights_or_formula_reference':'V21.233 STRATEGIES','source_policy':'MOOMOO_ONLY','producer_code_fingerprint':code,'strategy_config_fingerprint':cfg};wj(spec,OUT/'compact_model_spec.json');wj({'model_version':'ABCDE_COMPACT_V1','continuity_pass':True,'drift_detected':False},OUT/'model_version_audit.json');wj({'legacy_20260713_source_class':'LEGACY_ABCDE_RETAINED_SNAPSHOT','values_modified':False,'production_provenance_recoverable':False,'forward_observation_eligible':True,'production_reference_eligible':False},OUT/'legacy_reclassification_audit.json')
 lm=LEG/'real_abcde_manifest.json';leg=json.loads(lm.read_text()) if lm.exists() else {};leg['semantic_status']='LEGACY_ABCDE_RETAINED_SNAPSHOT_HISTORY';leg['production_provenance_recoverable']=False;wj(leg,lm)
 man={'model_version':'ABCDE_COMPACT_V1','signal_date_count':int(allx.signal_date.nunique()),'row_count':int(len(allx)),'start_date':str(allx.signal_date.min().date()),'end_date':str(allx.signal_date.max().date()),'producer_code_fingerprint':code};wj(man,CAN/'abcde_compact_v1_manifest.json')
 s={'final_status':'PASS','final_decision':'INSUFFICIENT_COMPACT_FORWARD_DATA','active_production_score_model':'ABCDE_COMPACT_V1','date_2026_07_23_compact_source_verified':True,'date_2026_07_23_compact_forward_eligible':True,'date_2026_07_23_compact_history_inserted':bool(len(new)),'compact_history_new_date_count':int(new.signal_date.nunique()),'compact_history_new_row_count':int(len(new)),'compact_history_row_count':int(len(allx)),'compact_history_signal_date_count':int(allx.signal_date.nunique()),'compact_history_conflict_count':0,'compact_score_formula_modified':False,'compact_factor_weight_modified':False,'compact_ranking_rule_modified':False,'legacy_and_compact_history_separated':True,'compact_written_to_legacy_history':False};wj(s,OUT/'summary.json');wj({'status':'COMPLETED',**s},OUT/'run_manifest.json');print(json.dumps(s));return s
if __name__=='__main__':run()
