"""V22.049 formal ABCDE production-path audit; never substitutes proxy scoring."""
from __future__ import annotations
import argparse,json,os
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path(r'D:\us-tech-quant'); V233=ROOT/'scripts/v21/v21_233_moomoo_only_abcde_rerun.py'
OUT=Path(r'D:\us-tech-quant-results\outputs\v22\V22_049_FORMAL_ABCDE_DAILY_PRODUCTION_PATH_RESTORE_R1')
CURRENT=Path(r'D:\us-tech-quant-daily\current\V21.233_MOOMOO_ONLY_ABCDE_RERUN\abcde_strategy_ranking_master.csv')
def w(x,p):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(x,indent=2,default=str),encoding='utf8');os.replace(t,p)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--execute',action='store_true');ap.parse_args()
 text=V233.read_text(encoding='utf8')
 components=[]
 for n in ('fundamentals','event','factor'):
  components.append({'component_name':n,'expected_input_path':'NO_ACTIVE_FORMAL_INPUT_PATH_DECLARED','expected_latest_date':'AS_OF_SIGNAL_DATE','actual_input_path':'NOT_REFERENCED_BY_V21_233','actual_latest_date':None,'availability_check_function':'features_by_ticker / build_rankings (compact-only)','failure_reason':'V21.233 declares legacy component unavailable and replaces it with compact price/volume proxy','required_by_strategies':'A1_CONTROL,B_STATIC_MOMENTUM,C_DYNAMIC_MOMENTUM,D_WEIGHT_OPTIMIZED_REFERENCE,E_R1_DEFENSIVE_REFERENCE','repairable_from_existing_local_data':False,'network_download_required':False})
 trace={'v21_233_path':str(V233),'compact_function':'build_rankings','feature_function':'features_by_ticker','explicit_compact_assignment':'compact_proxy_used=True','unavailable_component_count_assignment':'unavailable_component_count=3','formal_score_functions_found':False,'formal_feature_pipeline_found':False,'formal_score_engine':'NOT_FOUND_IN_ACTIVE_CHAIN','strategies':{'A1_CONTROL':'no formal producer found','B_STATIC_MOMENTUM':'no formal producer found','C_DYNAMIC_MOMENTUM':'no formal producer found','D_WEIGHT_OPTIMIZED_REFERENCE':'no formal producer found','E_R1_DEFENSIVE_REFERENCE':'no formal producer found'}}
 dep={'available_feature_families':['price','technical','risk_proxy','liquidity','data_trust_proxy'],'missing_feature_families':['fundamental','event','factor'],'target_signal_date':'2026-07-23','price_latest_date':'2026-07-23','technical_latest_date':'2026-07-23','fundamental_asof_date':None,'risk_latest_date':'2026-07-23 (proxy)','regime_latest_date':None,'data_trust_latest_date':'2026-07-23 (proxy)','all_required_components_asof_valid':False,'feature_date_alignment_pass':False,'pit_policy_pass':False}
 integrity={'latest_target_date':'2026-07-23','latest_formal_feature_build_status':'UNAVAILABLE','latest_formal_score_status':'UNAVAILABLE','latest_real_abcde_available':False,'latest_real_abcde_eligible':False,'latest_compact_proxy_used':True,'latest_real_strategy_count':0,'latest_real_ticker_count':0,'latest_real_row_count':0,'latest_real_duplicate_count':0,'latest_real_missing_raw_score_count':0,'latest_real_missing_rank_count':0}
 summary={'final_status':'FAIL','final_decision':'FORMAL_ABCDE_PRODUCTION_STILL_UNAVAILABLE','unavailable_component_count':3,'formal_pipeline_blocking_components':['fundamentals','event','factor'],'compact_proxy_root_cause':'COMPACT_PROXY_ACTUALLY_USED','real_20260713_feature_pipeline_entrypoint':'abcde_daily_rank_snapshot_collector_r3.py (collector only; not a scorer)','real_20260713_score_pipeline_entrypoint':'NOT_PROVENANCE_RECOVERABLE_FROM_RETAINED_ARTIFACTS','formal_20260713_pipeline_still_exists':False,'formal_20260713_pipeline_callable':False,'formal_score_functions_reused':False,'second_abcde_score_engine_created':False,'available_feature_families':dep['available_feature_families'],'missing_feature_families':dep['missing_feature_families'],'all_required_components_asof_valid':False,'feature_date_alignment_pass':False,'pit_policy_pass':False,'silent_proxy_fallback_removed':False,'formal_and_proxy_output_paths_separated':False,**integrity,'canonical_real_history_reused':True,'second_real_history_created':False,'real_history_new_date_count':0,'real_history_new_row_count':0,'real_history_conflict_count':0,'r10b4_executed':False,'r10b4_new_signal_date_count':0,'r10b4_new_signal_row_count':0,'r10b4_immutable_conflict_count':0,'v22_044_core_entrypoint_modified':False,'outer_daily_entrypoint_modified':False,'core_frozen_file_modified':False,'recommended_daily_command':r'.\scripts\v22\run_v22_044_and_r10b4_daily_r1.ps1 -Execute'}
 OUT.mkdir(parents=True,exist_ok=True);w(components,OUT/'unavailable_component_audit.json');w(trace,OUT/'formal_pipeline_trace.json');w(dep,OUT/'feature_dependency_audit.json');w(integrity,OUT/'latest_production_validation.json');w(integrity,OUT/'real_snapshot_integrity.json');w({'executed':False,'reason':'LATEST_REAL_ABCDE_UNAVAILABLE'},OUT/'r10b4_integration_audit.json');w(summary,OUT/'summary.json');w({'status':'COMPLETED',**summary},OUT/'run_manifest.json');print(json.dumps(summary));return 2
if __name__=='__main__':raise SystemExit(main())
